<a href="https://colab.research.google.com/github/simonlim563/asl-ml-immersion/blob/master/Social_sol/TH/Srichand/Female_XTH25-1533_Srichand_Magic%20Matte%20Collection%206s_171025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import requests
from pathlib import Path
import json
from google.auth import default
import os
import pandas as pd
from datetime import date, timedelta, datetime

from google.cloud import storage
import os
from google.oauth2 import service_account
from google.cloud import bigquery
from google.cloud import secretmanager
import numpy as np

import requests
from pathlib import Path
import json
from io import StringIO



import datetime
from zoneinfo import ZoneInfo

In [2]:
sg_time = datetime.datetime.now(ZoneInfo('Asia/Singapore'))
print(sg_time)

2025-10-17 12:56:00.895242+08:00

In [3]:
#Initialising start and end dates for report pulling
r_start_date = "2025-10-09"
yesterday = date.today() - timedelta(days=1)
r_end_date = yesterday.strftime('%Y-%m-%d')
today = date.today().strftime('%Y-%m-%d')

In [4]:
print(r_start_date,r_end_date,today)

2025-10-09 2025-10-16 2025-10-17

## Pulling the Brand Pulse report

In [5]:
all_secret_key = '6551c53e60299b053e1012a96c80431eeef233b0e9491c1c6c4adc98e81bb13a'


all_metrics="incrementalReach,impressions,uniqueReach,reach,spend"
## Meta, snap & tiktok Smartly reports
api_urls = {
"FOUNDATION_Female_XTH25-1533":f"https://api.smartly.io/stats/v2/brand-pulse/658870?api_token={all_secret_key}&timeframe={r_start_date}:{r_end_date}&metrics={all_metrics}",
"FOUNDATION_Male_XTH25-1533":f"https://api.smartly.io/stats/v2/brand-pulse/665525?api_token={all_secret_key}&timeframe={r_start_date}:{r_end_date}&metrics={all_metrics}",
"Concealer_Male_XTH25-1533":f"https://api.smartly.io/stats/v2/brand-pulse/665530?api_token={all_secret_key}&timeframe={r_start_date}:{r_end_date}&metrics={all_metrics}",
"Concealer_Female_XTH25-1533":f"https://api.smartly.io/stats/v2/brand-pulse/658879?api_token={all_secret_key}&timeframe={r_start_date}:{r_end_date}&metrics={all_metrics}"

}

api_headers = {
"FOUNDATION_Female_XTH25-1533": {"Authorization": "Bearer " + all_secret_key},
"FOUNDATION_Male_XTH25-1533": {"Authorization": "Bearer " + all_secret_key},
"Concealer_Male_XTH25-1533": {"Authorization": "Bearer " + all_secret_key},
"Concealer_Female_XTH25-1533": {"Authorization": "Bearer " + all_secret_key}
}

In [6]:
## Consolidating all the platform data (Meta, Snap & TikTok)
def reporting_api(api_url, platform, headers):
    response = requests.get(api_url, headers=headers)
    df = None  # Initialize df to None

    if response.status_code == 200:
        print(f"✅ Report for {platform} retrieved successfully!")
        df = pd.read_csv(StringIO(response.text))
        df["Platform"] = platform
    else:
        print(f"❌ Failed to retrieve report for {platform}. Status code: {response.status_code}")
        print(f"Response: {response.text}")

    return df

In [7]:
# --- Collect all reports into one combined DataFrame ---
all_dfs = []  # list to hold all successful DataFrames

for platform, api_url in api_urls.items():
    headers = api_headers.get(platform)
    if headers:
        df = reporting_api(api_url, platform, headers)
        if df is not None:
            all_dfs.append(df)

# Combine all reports
if all_dfs:
    combined_df_bp = pd.concat(all_dfs, ignore_index=True)
    print("✅ All reports combined successfully!")
else:
    combined_df_bp = pd.DataFrame()  # fallback if nothing retrieved
    print("⚠️ No reports were successfully retrieved.")

✅ Report for FOUNDATION_Female_XTH25-1533 retrieved successfully!
✅ Report for FOUNDATION_Male_XTH25-1533 retrieved successfully!
✅ Report for Concealer_Male_XTH25-1533 retrieved successfully!
✅ Report for Concealer_Female_XTH25-1533 retrieved successfully!
✅ All reports combined successfully!

In [8]:
combined_df_bp.shape

(32, 17)

In [9]:
df_FOUNDATION_Female = combined_df_bp[combined_df_bp['Platform']=="FOUNDATION_Female_XTH25-1533"]
df_FOUNDATION_Male = combined_df_bp[combined_df_bp['Platform']=="FOUNDATION_Male_XTH25-1533"]
df_Concealer_Male = combined_df_bp[combined_df_bp['Platform']=="Concealer_Male_XTH25-1533"]
df_Concealer_Female = combined_df_bp[combined_df_bp['Platform']=="Concealer_Female_XTH25-1533"]

## Pulling the standard Smartly report

In [31]:
token_id_standard = '86d9a8ccf687b02ac448016bb2ef819b'

## Meta, snap & tiktok Smartly reports
api_urls = {"XTH25-1533_Srichand_Magic Matte Collection 6s_standard":f"https://api.smartly.io/stats/v2/view/665544?token={token_id_standard}&timeframe={r_start_date}:{r_end_date}&timezone=Asia/Singapore&format=json"}

api_headers = {
"XTH25-1533_Srichand_Magic Matte Collection 6s_standard": {"Authorization": "Bearer " + token_id_standard}
}

In [32]:
## consolidating all the platform data (meta, snap & tiktok)
def reporting_api(api_url, platform, headers):
    response = requests.get(api_url, headers=headers)
    df_standard = None  # Initialize df to None

    if response.status_code == 200:
        print(f"Report for {platform} retrieved successfully!")
        data = response.json()

        headers = data['headers']
        report = data['report']

        df_standard = pd.DataFrame(report, columns=headers)
        df_standard['Platform'] = platform

    else:
        print(f"Failed to retrieve report for {platform}. Status code: {response.status_code}")
        print(f"Response: {response.text}")

    return df_standard

In [33]:
all_dfs = []
for platform, api_url in api_urls.items():
    headers = api_headers.get(platform)  # Get the headers for this platform
    if headers: # Check if headers exist for the platform
        df_standard = reporting_api(api_url, platform, headers)
        if df_standard is not None:
            all_dfs.append(df_standard)
    else:
        print(f"No headers found for platform: {platform}")

Report for XTH25-1533_Srichand_Magic Matte Collection 6s_standard retrieved successfully!

In [34]:
# Standardize columns
all_columns = set().union(*(df_1.columns for df_1 in all_dfs))  # Get all unique column names across all DataFrames

# Align all DataFrames to have the same columns
for i, df_1 in enumerate(all_dfs):
    missing_columns = all_columns - set(df_1.columns)  # Find missing columns in the current DataFrame
    print(missing_columns)
    all_dfs[i] = df_1

# Concatenate DataFrames
if all_dfs:
    df_all = pd.concat(all_dfs, ignore_index=True)
    df_all.to_csv("XTH25-1533_Srichand_Magic Matte Collection 6s_standard.csv", index=False)
    print("Combined report saved to XTH25-1533_Srichand_Magic Matte Collection 6s_standard.csv")
else:
    print("No reports were successfully retrieved.")

set()
Combined report saved to XTH25-1533_Srichand_Magic Matte Collection 6s_standard.csv

In [35]:
df_all.tail()

,Advertising Platform,Campaign ID,Campaign,Campaign ID,Ad Set ID,Ad Set,Ad Set ID,Ad ID,Ad,Ad ID,Date,Campaign Daily Budget,Campaign Lifetime Budget,Ad Set Daily Budget,Ad Set Lifetime Budget,Impressions,Spend,Platform
117,tiktok,1846143236938850,XTH25-1533_Srichand_17-31Oct_Magic Matte Colle...,1846143236938850,1846143236939922,Magic Matte Audience 1: Core target - Female,1846143236939922,1846143236939938,New Main&Fashion: Video 15sec & 6sec + KV : Co...,1846143236939938,None,0,0,0,NaN,0,0.0,XTH25-1533_Srichand_Magic Matte Collection 6s_...
118,tiktok,1846197293534449,XTH25-1533_Srichand_17-31Oct_Magic Matte Colle...,1846197293534449,1846197293535521,Magic Matte Audience 1: Core target - Male,1846197293535521,1846197293535537,New Main&Fashion: Video 15sec & 6sec + KV : Co...,1846197293535537,None,0,0,0,NaN,0,0.0,XTH25-1533_Srichand_Magic Matte Collection 6s_...
119,tiktok,1846200255150241,XTH25-1533_Srichand_17-31Oct_Magic Matte Colle...,1846200255150241,1846200255150257,Magic Matte Audience 2: RTG,1846200255150257,1846200255152385,New Main&Fashion: Video 15sec & 6sec + KV : Fo...,1846200255152385,None,0,0,0,NaN,0,0.0,XTH25-1533_Srichand_Magic Matte Collection 6s_...
120,tiktok,1846200255150241,XTH25-1533_Srichand_17-31Oct_Magic Matte Colle...,1846200255150241,1846200255152401,Magic Matte Audience 1: Core target - Female,1846200255152401,1846200255152417,New Main&Fashion: Video 15sec & 6sec + KV : Fo...,1846200255152417,None,0,0,0,NaN,0,0.0,XTH25-1533_Srichand_Magic Matte Collection 6s_...
121,tiktok,1846200445314081,XTH25-1533_Srichand_17-31Oct_Magic Matte Colle...,1846200445314081,1846200445314097,Magic Matte Audience 1: Core target - Male,1846200445314097,1846200445315137,New Main&Fashion: Video 15sec & 6sec + KV : Fo...,1846200445315137,None,0,0,0,NaN,0,0.0,XTH25-1533_Srichand_Magic Matte Collection 6s_...

In [36]:
# Keep only first occurrence of each column as there is some duplicate columns
df_all = df_all.loc[:, ~df_all.columns.duplicated()]

In [37]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Advertising Platform      122 non-null    object
 1   Campaign ID               122 non-null    object
 2   Campaign                  122 non-null    object
 3   Ad Set ID                 122 non-null    object
 4   Ad Set                    122 non-null    object
 5   Ad ID                     122 non-null    object
 6   Ad                        122 non-null    object
 7   Date                      109 non-null    object
 8   Campaign Daily Budget     122 non-null    int64
 9   Campaign Lifetime Budget  122 non-null    int64
 10  Ad Set Daily Budget       122 non-null    int64
 11  Ad Set Lifetime Budget    68 non-null     float64
 12  Impressions               122 non-null    int64
 13  Spend                     122 non-null    float64
 14  Platform                  122 non-null    object
dtypes: float64(2), int64(4), object(9)
memory usage: 14.4+ KB

In [38]:
df_standard_report = df_all.copy()

In [39]:
df_standard_report = df_standard_report.drop(
columns=['Campaign Lifetime Budget', 'Ad Set Daily Budget',
         'Campaign Daily Budget', 'Ad Set Lifetime Budget']
).reset_index(drop=True)

In [40]:
df_standard_report.head()

,Advertising Platform,Campaign ID,Campaign,Ad Set ID,Ad Set,Ad ID,Ad,Date,Impressions,Spend,Platform
0,facebook,120232857671770122,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,Old Main&Fashion: Video 6sec : Concealer (Focus),2025-10-09,79735,744.44,XTH25-1533_Srichand_Magic Matte Collection 6s_...
1,facebook,120232857671770122,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,Old Main&Fashion: Video 6sec : Concealer (Focus),2025-10-10,66669,615.00,XTH25-1533_Srichand_Magic Matte Collection 6s_...
2,facebook,120232857671770122,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,Old Main&Fashion: Video 6sec : Concealer (Focus),2025-10-11,46098,417.68,XTH25-1533_Srichand_Magic Matte Collection 6s_...
3,facebook,120232857671770122,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,Old Main&Fashion: Video 6sec : Concealer (Focus),2025-10-12,69228,617.98,XTH25-1533_Srichand_Magic Matte Collection 6s_...
4,facebook,120232857671770122,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,Old Main&Fashion: Video 6sec : Concealer (Focus),2025-10-13,55731,484.88,XTH25-1533_Srichand_Magic Matte Collection 6s_...

In [41]:
df_standard_report_end = df_standard_report.groupby(['Advertising Platform','Campaign','Campaign ID','Ad Set ID', 'Ad Set','Ad ID','Date'])[['Impressions', 'Spend']].sum().reset_index()
df_standard_report_end

,Advertising Platform,Campaign,Campaign ID,Ad Set ID,Ad Set,Ad ID,Date,Impressions,Spend
0,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,2025-10-09,79735,744.44
1,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,2025-10-10,66669,615.00
2,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,2025-10-11,46098,417.68
3,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,2025-10-12,69228,617.98
4,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,2025-10-13,55731,484.88
...,...,...,...,...,...,...,...,...,...
104,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995522,2025-10-12,112885,854.61
105,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995522,2025-10-13,111983,843.50
106,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995522,2025-10-14,95131,831.31
107,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995522,2025-10-15,98913,916.14
108,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995522,2025-10-16,123025,1086.57

In [42]:

#Splitting the report into respective campaigns

campaign_names_to_keep_CONCEALER_FEMALE = ["XTH25-1533_Srichand_Magic Matte Collection 6s CONCEALER FEMALE_CPM_Integrated Social_Oct'25_02076462", "XTH25-1533_Srichand_Magic Matte Collection 6s Concealer FEMALE_CPM_Integrated Social_Oct'25 _02076462"]
df_standard_report_end_Concealer_Female = df_standard_report_end[df_standard_report_end['Campaign'].isin(campaign_names_to_keep_CONCEALER_FEMALE)]

campaign_names_to_keep_foundation_female = ["120232852889250122", "1845308633305154"]
df_standard_report_end_FOUNDATION_Female = df_standard_report_end[df_standard_report_end['Campaign ID'].isin(campaign_names_to_keep_foundation_female)]

campaign_names_to_keep_foundation_male = ["XTH25-1533_Srichand_Magic Matte Collection 6s FOUNDATION MALE_CPM_Integrated Social_Oct'25_02076462", "XTH25-1533_Srichand_Magic Matte Collection 6s FOUNDATION MALE_CPM_Integrated Social_Oct'25_02076462"]
df_standard_report_end_FOUNDATION_Male = df_standard_report_end[df_standard_report_end['Campaign'].isin(campaign_names_to_keep_foundation_male)]


campaign_names_to_keep_concealer_male = ["XTH25-1533_Srichand_Magic Matte Collection 6s CONCEALER MALE_CPM_Integrated Social_Oct'25_02076462", "XTH25-1533_Srichand_Magic Matte Collection 6s Concealer MALE_CPM_Integrated Social_Oct'25_02076462"]
df_standard_report_end_Concealer_Male = df_standard_report_end[df_standard_report_end['Campaign'].isin(campaign_names_to_keep_concealer_male)]

In [43]:
df_standard_report_end_Concealer_Female

,Advertising Platform,Campaign,Campaign ID,Ad Set ID,Ad Set,Ad ID,Date,Impressions,Spend
0,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,2025-10-09,79735,744.44
1,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,2025-10-10,66669,615.00
2,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,2025-10-11,46098,417.68
3,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,2025-10-12,69228,617.98
4,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,2025-10-13,55731,484.88
5,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,2025-10-14,31831,268.32
6,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,2025-10-15,58120,521.44
7,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,2025-10-16,60682,538.46
8,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233009466490122,Magic Matte Audience 1: Core target Female IG,120233009466480122,2025-10-10,4466,40.86
9,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233009466490122,Magic Matte Audience 1: Core target Female IG,120233009466480122,2025-10-11,4757,43.64
10,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233009466490122,Magic Matte Audience 1: Core target Female IG,120233009466480122,2025-10-12,7169,64.83
11,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233009466490122,Magic Matte Audience 1: Core target Female IG,120233009466480122,2025-10-13,5594,48.91
12,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233009466490122,Magic Matte Audience 1: Core target Female IG,120233009466480122,2025-10-14,7623,65.75
13,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233009466490122,Magic Matte Audience 1: Core target Female IG,120233009466480122,2025-10-15,27899,254.12
14,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233009466490122,Magic Matte Audience 1: Core target Female IG,120233009466480122,2025-10-16,34075,308.73
15,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010194080122,Magic Matte Audience 2: RTG FB,120233010194070122,2025-10-10,34739,313.59
16,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010194080122,Magic Matte Audience 2: RTG FB,120233010194070122,2025-10-11,58673,528.88
17,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010194080122,Magic Matte Audience 2: RTG FB,120233010194070122,2025-10-12,51473,459.35
18,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010194080122,Magic Matte Audience 2: RTG FB,120233010194070122,2025-10-13,63803,554.73
19,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010194080122,Magic Matte Audience 2: RTG FB,120233010194070122,2025-10-14,67383,569.23
20,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010194080122,Magic Matte Audience 2: RTG FB,120233010194070122,2025-10-15,114190,1017.14
21,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010194080122,Magic Matte Audience 2: RTG FB,120233010194070122,2025-10-16,133364,1180.74
22,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010450860122,Magic Matte Audience 2: RTG IG,120233010450840122,2025-10-10,14690,135.09
23,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010450860122,Magic Matte Audience 2: RTG IG,120233010450840122,2025-10-11,18440,168.80
24,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010450860122,Magic Matte Audience 2: RTG IG,120233010450840122,2025-10-12,31220,282.34
25,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010450860122,Magic Matte Audience 2: RTG IG,120233010450840122,2025-10-13,24748,217.59
26,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010450860122,Magic Matte Audience 2: RTG IG,120233010450840122,2025-10-14,26384,228.06
27,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010450860122,Magic Matte Audience 2: RTG IG,120233010450840122,2025-10-15,80079,729.97
28,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010450860122,Magic Matte Audience 2: RTG IG,120233010450840122,2025-10-16,59627,539.45
65,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845309611569346,Magic Matte Audience 1: Core target - Female,1845403665943713,2025-10-09,107123,1214.86
66,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845309611569346,Magic Matte Audience 1: Core target - Female,1845403665943713,2025-10-10,96635,1105.20
67,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845309611569346,Magic Matte Audience 1: Core target - Female,1845403665943713,2025-10-11,96884,926.31
68,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845309611569346,Magic Matte Audience 1: Core target - Female,1845403665943713,2025-10-12,103492,918.57
69,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845309611569346,Magic Matte Audience 1: Core target - Female,1845403665943713,2025-10-13,109584,968.12
70,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845309611569346,Magic Matte Audience 1: Core target - Female,1845403665943713,2025-10-14,104848,1043.38
71,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845309611569346,Magic Matte Audience 1: Core target - Female,1845403665943713,2025-10-15,257043,3005.82
72,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845309611569346,Magic Matte Audience 1: Core target - Female,1845403665943713,2025-10-16,263382,2950.81
73,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845588355711042,Magic Matte Audience 2: RTG,1845588355711058,2025-10-10,8201,103.61
74,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845588355711042,Magic Matte Audience 2: RTG,1845588355711058,2025-10-11,25885,250.02
75,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845588355711042,Magic Matte Audience 2: RTG,1845588355711058,2025-10-12,32944,293.35
76,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845588355711042,Magic Matte Audience 2: RTG,1845588355711058,2025-10-13,26912,236.81
77,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845588355711042,Magic Matte Audience 2: RTG,1845588355711058,2025-10-14,16388,164.18
78,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845588355711042,Magic Matte Audience 2: RTG,1845588355711058,2025-10-15,29751,346.01
79,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845588355711042,Magic Matte Audience 2: RTG,1845588355711058,2025-10-16,28950,320.20

In [44]:
df_standard_report_end_FOUNDATION_Female

,Advertising Platform,Campaign,Campaign ID,Ad Set ID,Ad Set,Ad ID,Date,Impressions,Spend
43,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120232852889220122,Magic Matte Audience 1: Core target Female,120232852889130122,2025-10-09,113575,1301.84
44,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120232852889220122,Magic Matte Audience 1: Core target Female,120232852889130122,2025-10-10,122353,1196.00
45,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120232852889220122,Magic Matte Audience 1: Core target Female,120232852889130122,2025-10-11,82873,763.09
46,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120232852889220122,Magic Matte Audience 1: Core target Female,120232852889130122,2025-10-12,96821,880.04
47,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120232852889220122,Magic Matte Audience 1: Core target Female,120232852889130122,2025-10-13,84556,758.37
48,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120232852889220122,Magic Matte Audience 1: Core target Female,120232852889130122,2025-10-14,92352,802.72
49,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120232852889220122,Magic Matte Audience 1: Core target Female,120232852889130122,2025-10-15,204689,1900.13
50,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120232852889220122,Magic Matte Audience 1: Core target Female,120232852889130122,2025-10-16,236138,2201.59
51,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120233010669040122,Magic Matte Audience 2: RTG,120233010669030122,2025-10-10,46737,433.46
52,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120233010669040122,Magic Matte Audience 2: RTG,120233010669030122,2025-10-11,75614,692.60
53,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120233010669040122,Magic Matte Audience 2: RTG,120233010669030122,2025-10-12,132364,1196.48
54,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120233010669040122,Magic Matte Audience 2: RTG,120233010669030122,2025-10-13,131104,1164.10
55,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120233010669040122,Magic Matte Audience 2: RTG,120233010669030122,2025-10-14,111200,960.49
56,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120233010669040122,Magic Matte Audience 2: RTG,120233010669030122,2025-10-15,219680,2015.24
57,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120233010669040122,Magic Matte Audience 2: RTG,120233010669030122,2025-10-16,231136,2153.85
87,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845308633305170,Magic Matte Audience 1: Core target - Female,1845403802316866,2025-10-09,158817,1772.41
88,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845308633305170,Magic Matte Audience 1: Core target - Female,1845403802316866,2025-10-10,133107,1532.83
89,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845308633305170,Magic Matte Audience 1: Core target - Female,1845403802316866,2025-10-11,133699,1271.53
90,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845308633305170,Magic Matte Audience 1: Core target - Female,1845403802316866,2025-10-12,161698,1432.02
91,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845308633305170,Magic Matte Audience 1: Core target - Female,1845403802316866,2025-10-13,166314,1466.04
92,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845308633305170,Magic Matte Audience 1: Core target - Female,1845403802316866,2025-10-14,147049,1476.33
93,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845308633305170,Magic Matte Audience 1: Core target - Female,1845403802316866,2025-10-15,274399,3180.54
94,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845308633305170,Magic Matte Audience 1: Core target - Female,1845403802316866,2025-10-16,272421,3050.07
95,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845588535235777,Magic Matte Audience 2: RTG,1845588535235793,2025-10-10,17820,226.37
96,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845588535235777,Magic Matte Audience 2: RTG,1845588535235793,2025-10-11,46943,446.86
97,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845588535235777,Magic Matte Audience 2: RTG,1845588535235793,2025-10-12,37520,334.60
98,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845588535235777,Magic Matte Audience 2: RTG,1845588535235793,2025-10-13,33167,294.28
99,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845588535235777,Magic Matte Audience 2: RTG,1845588535235793,2025-10-14,28552,286.19
100,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845588535235777,Magic Matte Audience 2: RTG,1845588535235793,2025-10-15,32697,377.92
101,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845588535235777,Magic Matte Audience 2: RTG,1845588535235793,2025-10-16,37240,411.05

In [45]:
df_standard_report_end_FOUNDATION_Male

,Advertising Platform,Campaign,Campaign ID,Ad Set ID,Ad Set,Ad ID,Date,Impressions,Spend
58,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233084770160122,120233084770200122,Magic Matte Audience 1: Core target Male FB,120233084770230122,2025-10-10,30069,349.60
59,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233084770160122,120233084770200122,Magic Matte Audience 1: Core target Male FB,120233084770230122,2025-10-11,76122,682.08
60,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233084770160122,120233084770200122,Magic Matte Audience 1: Core target Male FB,120233084770230122,2025-10-12,94676,838.57
61,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233084770160122,120233084770200122,Magic Matte Audience 1: Core target Male FB,120233084770230122,2025-10-13,103845,900.52
62,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233084770160122,120233084770200122,Magic Matte Audience 1: Core target Male FB,120233084770230122,2025-10-14,89723,751.86
63,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233084770160122,120233084770200122,Magic Matte Audience 1: Core target Male FB,120233084770230122,2025-10-15,136414,1167.58
64,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233084770160122,120233084770200122,Magic Matte Audience 1: Core target Male FB,120233084770230122,2025-10-16,82210,709.79
102,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995522,2025-10-10,34824,339.93
103,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995522,2025-10-11,106833,885.36
104,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995522,2025-10-12,112885,854.61
105,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995522,2025-10-13,111983,843.50
106,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995522,2025-10-14,95131,831.31
107,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995522,2025-10-15,98913,916.14
108,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995522,2025-10-16,123025,1086.57

In [46]:
df_standard_report_end_Concealer_Male

,Advertising Platform,Campaign,Campaign ID,Ad Set ID,Ad Set,Ad ID,Date,Impressions,Spend
29,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233085296140122,120233085296120122,Magic Matte Audience 1: Core target Male FB,120233085296180122,2025-10-10,7746,79.66
30,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233085296140122,120233085296120122,Magic Matte Audience 1: Core target Male FB,120233085296180122,2025-10-11,29187,262.66
31,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233085296140122,120233085296120122,Magic Matte Audience 1: Core target Male FB,120233085296180122,2025-10-12,40186,355.04
32,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233085296140122,120233085296120122,Magic Matte Audience 1: Core target Male FB,120233085296180122,2025-10-13,40994,348.71
33,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233085296140122,120233085296120122,Magic Matte Audience 1: Core target Male FB,120233085296180122,2025-10-14,44916,363.49
34,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233085296140122,120233085296120122,Magic Matte Audience 1: Core target Male FB,120233085296180122,2025-10-15,86404,742.50
35,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233085296140122,120233085296120122,Magic Matte Audience 1: Core target Male FB,120233085296180122,2025-10-16,95448,814.36
36,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233085296140122,120233085296170122,Magic Matte Audience 1: Core target Male IG,120233085296130122,2025-10-10,8196,78.96
37,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233085296140122,120233085296170122,Magic Matte Audience 1: Core target Male IG,120233085296130122,2025-10-11,10669,97.69
38,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233085296140122,120233085296170122,Magic Matte Audience 1: Core target Male IG,120233085296130122,2025-10-12,13034,116.71
39,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233085296140122,120233085296170122,Magic Matte Audience 1: Core target Male IG,120233085296130122,2025-10-13,9706,84.11
40,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233085296140122,120233085296170122,Magic Matte Audience 1: Core target Male IG,120233085296130122,2025-10-14,4961,41.38
41,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233085296140122,120233085296170122,Magic Matte Audience 1: Core target Male IG,120233085296130122,2025-10-15,14004,124.49
42,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233085296140122,120233085296170122,Magic Matte Audience 1: Core target Male IG,120233085296130122,2025-10-16,21866,190.24
80,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845588047313025,1845588047313041,Magic Matte Audience 1: Core target - Male,1845588047313057,2025-10-10,26313,250.90
81,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845588047313025,1845588047313041,Magic Matte Audience 1: Core target - Male,1845588047313057,2025-10-11,73629,616.69
82,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845588047313025,1845588047313041,Magic Matte Audience 1: Core target - Male,1845588047313057,2025-10-12,77430,592.59
83,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845588047313025,1845588047313041,Magic Matte Audience 1: Core target - Male,1845588047313057,2025-10-13,76901,579.60
84,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845588047313025,1845588047313041,Magic Matte Audience 1: Core target - Male,1845588047313057,2025-10-14,65224,568.67
85,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845588047313025,1845588047313041,Magic Matte Audience 1: Core target - Male,1845588047313057,2025-10-15,66458,608.50
86,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845588047313025,1845588047313041,Magic Matte Audience 1: Core target - Male,1845588047313057,2025-10-16,77461,680.59

## Transforming Brand Pulse report

In [47]:
df_Concealer_Female.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 24 to 31
Data columns (total 17 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Date                                    8 non-null      object
 1   Daily Incremental Reach (Deduplicated)  8 non-null      int64
 2   Daily Incremental Reach (Meta)          8 non-null      int64
 3   Daily Incremental Reach (TikTok)        8 non-null      int64
 4   Daily Impressions (All)                 8 non-null      int64
 5   Daily Impressions (Meta)                8 non-null      int64
 6   Daily Impressions (TikTok)              8 non-null      int64
 7   Daily Unique Reach (Overlapped)         8 non-null      int64
 8   Daily Unique Reach (Meta)               8 non-null      int64
 9   Daily Unique Reach (TikTok)             8 non-null      int64
 10  Daily Reach (Deduplicated)              8 non-null      int64
 11  Daily Reach (Meta)                      8 non-null      int64
 12  Daily Reach (TikTok)                    8 non-null      int64
 13  Daily Spend (All)                       8 non-null      float64
 14  Daily Spend (Meta)                      8 non-null      float64
 15  Daily Spend (TikTok)                    8 non-null      float64
 16  Platform                                8 non-null      object
dtypes: float64(3), int64(12), object(2)
memory usage: 1.1+ KB

In [48]:
df_Concealer_Female

,Date,Daily Incremental Reach (Deduplicated),Daily Incremental Reach (Meta),Daily Incremental Reach (TikTok),Daily Impressions (All),Daily Impressions (Meta),Daily Impressions (TikTok),Daily Unique Reach (Overlapped),Daily Unique Reach (Meta),Daily Unique Reach (TikTok),Daily Reach (Deduplicated),Daily Reach (Meta),Daily Reach (TikTok),Daily Spend (All),Daily Spend (Meta),Daily Spend (TikTok),Platform
24,2025-10-09,184486,78524,107149,186884,79735,107149,1187,77337,105962,184486,78524,107149,1959.30,744.44,1214.86,Concealer_Female_XTH25-1533
25,2025-10-10,183041,111390,75353,225400,120564,104836,1696,117125,99526,218347,118821,101222,2313.35,1104.54,1208.81,Concealer_Female_XTH25-1533
26,2025-10-11,199961,127968,75413,250737,127968,122769,2143,125825,116575,244543,127968,118718,2335.33,1159.00,1176.33,Concealer_Female_XTH25-1533
27,2025-10-12,219509,151733,81981,295526,159090,136436,2967,155817,129518,288302,158784,132485,2636.42,1424.50,1211.92,Concealer_Female_XTH25-1533
28,2025-10-13,210742,143046,77862,286372,149876,136496,2665,140381,129444,272490,143046,132109,2511.04,1306.11,1204.93,Concealer_Female_XTH25-1533
29,2025-10-14,169885,122895,64324,254457,133221,121236,2190,129232,115930,247352,131422,118120,2338.92,1131.36,1207.56,Concealer_Female_XTH25-1533
30,2025-10-15,385996,234384,194103,567082,280288,286794,10526,258256,267127,535909,268782,277653,5874.50,2522.67,3351.83,Concealer_Female_XTH25-1533
31,2025-10-16,402301,269303,180933,580048,287719,292329,10725,258578,271630,540933,269303,282355,5838.39,2567.38,3271.01,Concealer_Female_XTH25-1533

In [49]:
def transform_brand_pulse(df):
  """Transform brand pulse dataframe to long format"""

  # Convert Date to datetime
  df['Date'] = pd.to_datetime(df['Date'])

  platforms = ['Meta', 'TikTok']
  dfs = []

  for platform in platforms:
      temp_df = pd.DataFrame({
          'Date': df['Date'],
          'Daily_Incremental_Reach': df[f'Daily Incremental Reach ({platform})'],
          'Daily_Spend': df[f'Daily Spend ({platform})'],
          'Daily_Reach': df[f'Daily Reach ({platform})'],
          'Daily_deduplicated_incremental_Reach': df['Daily Incremental Reach (Deduplicated)'],
          'Platform': platform
      })
      dfs.append(temp_df)

  result = pd.concat(dfs, ignore_index=True).sort_values('Date', ascending=True).reset_index(drop=True)

  return result

# Apply to all dataframes
df_FOUNDATION_Female_transformed = transform_brand_pulse(df_FOUNDATION_Female)
df_FOUNDATION_Male_transformed = transform_brand_pulse(df_FOUNDATION_Male)
df_Concealer_Male_transformed = transform_brand_pulse(df_Concealer_Male)
df_Concealer_Female_transformed = transform_brand_pulse(df_Concealer_Female)

print("✅ All dataframes transformed")

✅ All dataframes transformed

/tmp/ipython-input-2901412155.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = pd.to_datetime(df['Date'])
/tmp/ipython-input-2901412155.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = pd.to_datetime(df['Date'])
/tmp/ipython-input-2901412155.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = pd.to_datetime(df['Date'])
/tmp/ipython-input-2901412155.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = pd.to_datetime(df['Date'])

In [50]:
# df['Date'] = pd.to_datetime(df['Date'])

In [51]:
# platforms = ['Meta', 'TikTok']

# dfs = []
# for platform in platforms:
#   temp_df = pd.DataFrame({
#       'Date': df['Date'],
#       'Daily_Incremental_Reach': df[f'Daily Incremental Reach ({platform})'],
#       'Daily_Spend': df[f'Daily Spend ({platform})'],
#       'Daily_Reach': df[f'Daily Reach ({platform})'],
#       'Daily_deduplicated_incremental_Reach': df['Daily Incremental Reach (Deduplicated)'],
#       'Platform': platform
#   })
#   dfs.append(temp_df)

# result_brand_pulse = pd.concat(dfs, ignore_index=True).sort_values('Date', ascending=False)

In [52]:
# result_brand_pulse.reset_index(drop=True, inplace=True)
# result_brand_pulse = result_brand_pulse.sort_values('Date', ascending=True)
# result_brand_pulse

In [53]:
# result_brand_pulse.groupby('Platform')['Daily_Spend'].sum()

## Adding new parameters for PBA inputs

In [54]:
def add_calculations(df):
  """Add all calculated columns to transformed dataframe"""

  # Calculate sum of daily incremental reach per date
  df['sum_daily_incremental_reach'] = df.groupby('Date')['Daily_Incremental_Reach'].transform('sum')

  # Calculate overlap
  df['deduplicated_incremental_overlap_reach'] = (
      df['sum_daily_incremental_reach'] - df['Daily_deduplicated_incremental_Reach']
  )

  # Drop temp column
  df = df.drop(columns=['sum_daily_incremental_reach'])

  # Calculate daily cost per reach
  df['Cost_per_incremental_reach'] = (
      df['Daily_Spend'] / df['Daily_Incremental_Reach']
  ).round(5)

  # Calculate percentage of daily deduplicated incremental reach
  df['Percentage_of_reach_deduplicated'] = (
      df['deduplicated_incremental_overlap_reach'] / df['Daily_Incremental_Reach']
  ).round(4)

  # Reach per $1000 spend
  df['Reach_spend_1000'] = (
      1000 / df['Cost_per_incremental_reach']
  ).round(2)

  # Estimate overlap incremental reach per $1000
  df['Estimate_overlap_reach_1000'] = (
      df['Reach_spend_1000'] * df['Percentage_of_reach_deduplicated']
  ).round(2)

  # Final actual deduplicated reach per $1000
  df['Actual_reach_1000'] = (
      df['Reach_spend_1000'] - df['Estimate_overlap_reach_1000']
  ).round(2)

  # Convert to PBA friendly value
  df['PBA_INPUT'] = (
      df['Actual_reach_1000'] * df['Daily_Spend']
  ) / 10**6

  return df

In [55]:
# Apply to all transformed dataframes
df_FOUNDATION_Female_transformed_1 = add_calculations(df_FOUNDATION_Female_transformed)
df_FOUNDATION_Male_transformed_1 = add_calculations(df_FOUNDATION_Male_transformed)
df_Concealer_Male_transformed_1 = add_calculations(df_Concealer_Male_transformed)
df_Concealer_Female_transformed_1 = add_calculations(df_Concealer_Female_transformed)

print("✅ Calculations added to all dataframes")

✅ Calculations added to all dataframes

In [103]:
# df_social = result_brand_pulse.copy()

In [104]:
# # Calculate sum of daily incremental reach per date
# df_social['sum_daily_incremental_reach'] = df_social.groupby('Date')['Daily_Incremental_Reach'].transform('sum')

# # Calculate overlap
# df_social['deduplicated_incremental_overlap_reach'] = df_social['sum_daily_incremental_reach'] - df_social['Daily_deduplicated_incremental_Reach']

# # Drop temp column if not needed
# df_social = df_social.drop(columns=['sum_daily_incremental_reach'])

# df_social.head()

In [105]:
# #Calculate the daily cost per reach
# df_social['Cost_per_incremental_reach'] = (df_social['Daily_Spend'] / df_social['Daily_Incremental_Reach']).round(5)


# #Calcuate the percentage of daily deduplicated incremental reach to its respective platform
# df_social['Percentage_of_reach_deduplicated'] = ((df_social['deduplicated_incremental_overlap_reach'] / df_social['Daily_Incremental_Reach'])).round(4)

# #Assumming a daily budget of $1000 what will the incremental reach be?
# df_social['Reach_spend_1000'] =  (1000/df_social['Cost_per_incremental_reach']).round(2)


# #Estimate the overlap incremental reach per $1000
# df_social['Estimate_overlap_reach_1000'] = (df_social['Reach_spend_1000']* df_social['Percentage_of_reach_deduplicated']).round(2)

# #Final actual deduplicated reach per $1000
# df_social['Actual_reach_1000'] = (df_social['Reach_spend_1000'] - df_social['Estimate_overlap_reach_1000']).round(2)

# #Convert to a PBA friendly value
# df_social['PBA_INPUT'] = (df_social['Actual_reach_1000'] * df_social['Daily_Spend'])/10**6

In [56]:
df_Concealer_Female_transformed_1

,Date,Daily_Incremental_Reach,Daily_Spend,Daily_Reach,Daily_deduplicated_incremental_Reach,Platform,deduplicated_incremental_overlap_reach,Cost_per_incremental_reach,Percentage_of_reach_deduplicated,Reach_spend_1000,Estimate_overlap_reach_1000,Actual_reach_1000,PBA_INPUT
0,2025-10-09,78524,744.44,78524,184486,Meta,1187,0.00948,0.0151,105485.23,1592.83,103892.40,77.341658
1,2025-10-09,107149,1214.86,107149,184486,TikTok,1187,0.01134,0.0111,88183.42,978.84,87204.58,105.941356
2,2025-10-10,111390,1104.54,118821,183041,Meta,3702,0.00992,0.0332,100806.45,3346.77,97459.68,107.648115
3,2025-10-10,75353,1208.81,101222,183041,TikTok,3702,0.01604,0.0491,62344.14,3061.10,59283.04,71.661932
4,2025-10-11,127968,1159.00,127968,199961,Meta,3420,0.00906,0.0267,110375.28,2947.02,107428.26,124.509353
5,2025-10-11,75413,1176.33,118718,199961,TikTok,3420,0.01560,0.0454,64102.56,2910.26,61192.30,71.982338
6,2025-10-12,151733,1424.50,158784,219509,Meta,14205,0.00939,0.0936,106496.27,9968.05,96528.22,137.504449
7,2025-10-12,81981,1211.92,132485,219509,TikTok,14205,0.01478,0.1733,67659.00,11725.30,55933.70,67.787170
8,2025-10-13,143046,1306.11,143046,210742,Meta,10166,0.00913,0.0711,109529.03,7787.51,101741.52,132.885617
9,2025-10-13,77862,1204.93,132109,210742,TikTok,10166,0.01548,0.1306,64599.48,8436.69,56162.79,67.672231
10,2025-10-14,122895,1131.36,131422,169885,Meta,17334,0.00921,0.1410,108577.63,15309.45,93268.18,105.519888
11,2025-10-14,64324,1207.56,118120,169885,TikTok,17334,0.01877,0.2695,53276.51,14358.02,38918.49,46.996412
12,2025-10-15,234384,2522.67,268782,385996,Meta,42491,0.01076,0.1813,92936.80,16849.44,76087.36,191.943300
13,2025-10-15,194103,3351.83,277653,385996,TikTok,42491,0.01727,0.2189,57903.88,12675.16,45228.72,151.598981
14,2025-10-16,269303,2567.38,269303,402301,Meta,47935,0.00953,0.1780,104931.79,18677.86,86253.93,221.446615
15,2025-10-16,180933,3271.01,282355,402301,TikTok,47935,0.01808,0.2649,55309.73,14651.55,40658.18,132.993313

## Converting to suitable format for PBA API ingestion

In [59]:
def final_transformation(df_bp, df_standard_1):
  # First, standardize platform names in both tables
  df_bp_renamed = df_bp.copy()
  df_bp_renamed['platform'] = df_bp_renamed['Platform'].str.lower().replace({'meta': 'facebook'})

  df_standard_1_renamed = df_standard_1.copy()
  df_standard_1_renamed['platform'] = df_standard_1_renamed['Advertising Platform'].str.lower()

  # Ensure Date columns are same type
  df_standard_1_renamed['Date'] = pd.to_datetime(df_standard_1_renamed['Date'])
  df_bp_renamed['Date'] = pd.to_datetime(df_bp_renamed['Date'])


  # Merge tables on platform
  result_end = df_standard_1_renamed.merge(
  df_bp_renamed[['Date', 'platform', 'PBA_INPUT']],
  on=['Date', 'platform'],  # ← Changed from 'platform' to list
  how='left'
  )


  return result_end

In [60]:
# Apply to all transformed dataframes
result_end_FOUNDATION_Female = final_transformation(df_FOUNDATION_Female_transformed_1,df_standard_report_end_FOUNDATION_Female)
result_end_FOUNDATION_Male = final_transformation(df_FOUNDATION_Male_transformed_1,df_standard_report_end_FOUNDATION_Male)
result_end_Concealer_Male = final_transformation(df_Concealer_Male_transformed_1,df_standard_report_end_Concealer_Male)
result_end_Concealer_Female = final_transformation(df_Concealer_Female_transformed_1,df_standard_report_end_Concealer_Female)

print("✅ End result created for all Magic Matte Collection 6s")

✅ End result created for all Magic Matte Collection 6s

In [61]:
result_end_Concealer_Female

,Advertising Platform,Campaign,Campaign ID,Ad Set ID,Ad Set,Ad ID,Date,Impressions,Spend,platform,PBA_INPUT
0,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,2025-10-09,79735,744.44,facebook,77.341658
1,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,2025-10-10,66669,615.00,facebook,107.648115
2,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,2025-10-11,46098,417.68,facebook,124.509353
3,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,2025-10-12,69228,617.98,facebook,137.504449
4,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,2025-10-13,55731,484.88,facebook,132.885617
5,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,2025-10-14,31831,268.32,facebook,105.519888
6,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,2025-10-15,58120,521.44,facebook,191.943300
7,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120232857671760122,Magic Matte Audience 1: Core target Female,120232857671780122,2025-10-16,60682,538.46,facebook,221.446615
8,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233009466490122,Magic Matte Audience 1: Core target Female IG,120233009466480122,2025-10-10,4466,40.86,facebook,107.648115
9,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233009466490122,Magic Matte Audience 1: Core target Female IG,120233009466480122,2025-10-11,4757,43.64,facebook,124.509353
10,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233009466490122,Magic Matte Audience 1: Core target Female IG,120233009466480122,2025-10-12,7169,64.83,facebook,137.504449
11,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233009466490122,Magic Matte Audience 1: Core target Female IG,120233009466480122,2025-10-13,5594,48.91,facebook,132.885617
12,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233009466490122,Magic Matte Audience 1: Core target Female IG,120233009466480122,2025-10-14,7623,65.75,facebook,105.519888
13,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233009466490122,Magic Matte Audience 1: Core target Female IG,120233009466480122,2025-10-15,27899,254.12,facebook,191.943300
14,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233009466490122,Magic Matte Audience 1: Core target Female IG,120233009466480122,2025-10-16,34075,308.73,facebook,221.446615
15,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010194080122,Magic Matte Audience 2: RTG FB,120233010194070122,2025-10-10,34739,313.59,facebook,107.648115
16,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010194080122,Magic Matte Audience 2: RTG FB,120233010194070122,2025-10-11,58673,528.88,facebook,124.509353
17,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010194080122,Magic Matte Audience 2: RTG FB,120233010194070122,2025-10-12,51473,459.35,facebook,137.504449
18,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010194080122,Magic Matte Audience 2: RTG FB,120233010194070122,2025-10-13,63803,554.73,facebook,132.885617
19,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010194080122,Magic Matte Audience 2: RTG FB,120233010194070122,2025-10-14,67383,569.23,facebook,105.519888
20,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010194080122,Magic Matte Audience 2: RTG FB,120233010194070122,2025-10-15,114190,1017.14,facebook,191.943300
21,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010194080122,Magic Matte Audience 2: RTG FB,120233010194070122,2025-10-16,133364,1180.74,facebook,221.446615
22,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010450860122,Magic Matte Audience 2: RTG IG,120233010450840122,2025-10-10,14690,135.09,facebook,107.648115
23,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010450860122,Magic Matte Audience 2: RTG IG,120233010450840122,2025-10-11,18440,168.80,facebook,124.509353
24,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010450860122,Magic Matte Audience 2: RTG IG,120233010450840122,2025-10-12,31220,282.34,facebook,137.504449
25,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010450860122,Magic Matte Audience 2: RTG IG,120233010450840122,2025-10-13,24748,217.59,facebook,132.885617
26,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010450860122,Magic Matte Audience 2: RTG IG,120233010450840122,2025-10-14,26384,228.06,facebook,105.519888
27,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010450860122,Magic Matte Audience 2: RTG IG,120233010450840122,2025-10-15,80079,729.97,facebook,191.943300
28,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232857671770122,120233010450860122,Magic Matte Audience 2: RTG IG,120233010450840122,2025-10-16,59627,539.45,facebook,221.446615
29,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845309611569346,Magic Matte Audience 1: Core target - Female,1845403665943713,2025-10-09,107123,1214.86,tiktok,105.941356
30,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845309611569346,Magic Matte Audience 1: Core target - Female,1845403665943713,2025-10-10,96635,1105.20,tiktok,71.661932
31,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845309611569346,Magic Matte Audience 1: Core target - Female,1845403665943713,2025-10-11,96884,926.31,tiktok,71.982338
32,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845309611569346,Magic Matte Audience 1: Core target - Female,1845403665943713,2025-10-12,103492,918.57,tiktok,67.787170
33,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845309611569346,Magic Matte Audience 1: Core target - Female,1845403665943713,2025-10-13,109584,968.12,tiktok,67.672231
34,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845309611569346,Magic Matte Audience 1: Core target - Female,1845403665943713,2025-10-14,104848,1043.38,tiktok,46.996412
35,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845309611569346,Magic Matte Audience 1: Core target - Female,1845403665943713,2025-10-15,257043,3005.82,tiktok,151.598981
36,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845309611569346,Magic Matte Audience 1: Core target - Female,1845403665943713,2025-10-16,263382,2950.81,tiktok,132.993313
37,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845588355711042,Magic Matte Audience 2: RTG,1845588355711058,2025-10-10,8201,103.61,tiktok,71.661932
38,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845588355711042,Magic Matte Audience 2: RTG,1845588355711058,2025-10-11,25885,250.02,tiktok,71.982338
39,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845588355711042,Magic Matte Audience 2: RTG,1845588355711058,2025-10-12,32944,293.35,tiktok,67.787170
40,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845588355711042,Magic Matte Audience 2: RTG,1845588355711058,2025-10-13,26912,236.81,tiktok,67.672231
41,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845588355711042,Magic Matte Audience 2: RTG,1845588355711058,2025-10-14,16388,164.18,tiktok,46.996412
42,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845588355711042,Magic Matte Audience 2: RTG,1845588355711058,2025-10-15,29751,346.01,tiktok,151.598981
43,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845309611568386,1845588355711042,Magic Matte Audience 2: RTG,1845588355711058,2025-10-16,28950,320.20,tiktok,132.993313

In [ ]:
# # First, standardize platform names in both tables
# df_social_renamed = df_social.copy()
# df_social_renamed['platform'] = df_social_renamed['Platform'].str.lower().replace({'meta': 'facebook'})

# df_standard_report_end_renamed = df_standard_report_end.copy()
# df_standard_report_end_renamed['platform'] = df_standard_report_end_renamed['Advertising Platform'].str.lower()

# # Merge tables on platform
# result_end = df_standard_report_end_renamed.merge(
# df_social_renamed[['Date', 'platform', 'PBA_INPUT']],
# on='platform',
# how='left'
# )

In [114]:
# result_end

## Creating final dataframe for PBA input for Concealer Female and push into Smartly

In [62]:
# Create final structure
df_final = pd.DataFrame({
'ad_unit_id': result_end_Concealer_Female['Ad ID'],
'event_name': 'XTH25-1533_Srichand_Concealer_Female_Pixel',
'event_date': result_end_Concealer_Female['Date'],
'ad_interaction_date': result_end_Concealer_Female['Date'],
'conversions': result_end_Concealer_Female['PBA_INPUT'],
'platform': result_end_Concealer_Female['platform']
})

In [63]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ad_unit_id           44 non-null     object
 1   event_name           44 non-null     object
 2   event_date           44 non-null     datetime64[ns]
 3   ad_interaction_date  44 non-null     datetime64[ns]
 4   conversions          44 non-null     float64
 5   platform             44 non-null     object
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 2.2+ KB

In [64]:
df_final['event_date'] = pd.to_datetime(df_final['event_date'])
df_final['event_date'] = df_final['event_date'].dt.strftime('%Y-%m-%d')

df_final['ad_interaction_date'] = pd.to_datetime(df_final['ad_interaction_date'])
df_final['ad_interaction_date'] = df_final['ad_interaction_date'].dt.strftime('%Y-%m-%d')

In [65]:
# # Sort by date first to ensure earliest is first
# df_final = df_final.sort_values('event_date')

# # Replace inf and NaN with earliest valid conversion per platform
# def replace_invalid_with_earliest(group):
#   # Get first value that is neither inf nor NaN
#   valid_values = group[(~np.isinf(group)) & (~np.isnan(group))]
#   if len(valid_values) > 0:
#       first_valid = valid_values.iloc[0]
#       # Replace both inf and NaN
#       return group.replace([float('inf'), -float('inf')], first_valid).fillna(first_valid)
#   return group

# df_final['conversions'] = df_final.groupby('platform')['conversions'].transform(replace_invalid_with_earliest)

In [66]:
df_final[df_final['platform'] == 'facebook']['ad_unit_id'].unique()

array(['120232857671780122', '120233009466480122', '120233010194070122',
       '120233010450840122'], dtype=object)

In [67]:
df_final[df_final['platform'] == 'tiktok']['ad_unit_id'].unique()

array(['1845403665943713', '1845588355711058'], dtype=object)

In [68]:
# Define which IDs to keep
selected_ids = ['120232857671780122', '1845588355711058']

PBA_result = df_final[df_final['ad_unit_id'].isin(selected_ids)]

In [69]:
PBA_result['conversions'] = PBA_result['conversions'].astype(int)
PBA_result.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15 entries, 0 to 43
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ad_unit_id           15 non-null     object
 1   event_name           15 non-null     object
 2   event_date           15 non-null     object
 3   ad_interaction_date  15 non-null     object
 4   conversions          15 non-null     int64
 5   platform             15 non-null     object
dtypes: int64(1), object(5)
memory usage: 840.0+ bytes

/tmp/ipython-input-2482821460.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PBA_result['conversions'] = PBA_result['conversions'].astype(int)

In [70]:
PBA_result['event_date'] = pd.to_datetime(PBA_result['event_date'])
PBA_result['event_date'] = PBA_result['event_date'].dt.strftime('%Y-%m-%d')

PBA_result['ad_interaction_date'] = pd.to_datetime(PBA_result['ad_interaction_date'])
PBA_result['ad_interaction_date'] = PBA_result['ad_interaction_date'].dt.strftime('%Y-%m-%d')

/tmp/ipython-input-1697232129.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PBA_result['event_date'] = pd.to_datetime(PBA_result['event_date'])
/tmp/ipython-input-1697232129.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PBA_result['event_date'] = PBA_result['event_date'].dt.strftime('%Y-%m-%d')
/tmp/ipython-input-1697232129.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PBA_result['ad_interaction_date'] = pd.to_datetime(PBA_result['ad_interaction_date'])
/tmp/ipython-input-1697232129.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PBA_result['ad_interaction_date'] = PBA_result['ad_interaction_date'].dt.strftime('%Y-%m-%d')

In [71]:
PBA_result

,ad_unit_id,event_name,event_date,ad_interaction_date,conversions,platform
0,120232857671780122,XTH25-1533_Srichand_Concealer_Female_Pixel,2025-10-09,2025-10-09,77,facebook
1,120232857671780122,XTH25-1533_Srichand_Concealer_Female_Pixel,2025-10-10,2025-10-10,107,facebook
2,120232857671780122,XTH25-1533_Srichand_Concealer_Female_Pixel,2025-10-11,2025-10-11,124,facebook
3,120232857671780122,XTH25-1533_Srichand_Concealer_Female_Pixel,2025-10-12,2025-10-12,137,facebook
4,120232857671780122,XTH25-1533_Srichand_Concealer_Female_Pixel,2025-10-13,2025-10-13,132,facebook
5,120232857671780122,XTH25-1533_Srichand_Concealer_Female_Pixel,2025-10-14,2025-10-14,105,facebook
6,120232857671780122,XTH25-1533_Srichand_Concealer_Female_Pixel,2025-10-15,2025-10-15,191,facebook
7,120232857671780122,XTH25-1533_Srichand_Concealer_Female_Pixel,2025-10-16,2025-10-16,221,facebook
37,1845588355711058,XTH25-1533_Srichand_Concealer_Female_Pixel,2025-10-10,2025-10-10,71,tiktok
38,1845588355711058,XTH25-1533_Srichand_Concealer_Female_Pixel,2025-10-11,2025-10-11,71,tiktok
39,1845588355711058,XTH25-1533_Srichand_Concealer_Female_Pixel,2025-10-12,2025-10-12,67,tiktok
40,1845588355711058,XTH25-1533_Srichand_Concealer_Female_Pixel,2025-10-13,2025-10-13,67,tiktok
41,1845588355711058,XTH25-1533_Srichand_Concealer_Female_Pixel,2025-10-14,2025-10-14,46,tiktok
42,1845588355711058,XTH25-1533_Srichand_Concealer_Female_Pixel,2025-10-15,2025-10-15,151,tiktok
43,1845588355711058,XTH25-1533_Srichand_Concealer_Female_Pixel,2025-10-16,2025-10-16,132,tiktok

In [72]:
PBA_result.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15 entries, 0 to 43
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ad_unit_id           15 non-null     object
 1   event_name           15 non-null     object
 2   event_date           15 non-null     object
 3   ad_interaction_date  15 non-null     object
 4   conversions          15 non-null     int64
 5   platform             15 non-null     object
dtypes: int64(1), object(5)
memory usage: 1.4+ KB

In [73]:
PBA_result = PBA_result[(PBA_result['event_date'] == r_end_date)]
PBA_result

,ad_unit_id,event_name,event_date,ad_interaction_date,conversions,platform
7,120232857671780122,XTH25-1533_Srichand_Concealer_Female_Pixel,2025-10-16,2025-10-16,221,facebook
43,1845588355711058,XTH25-1533_Srichand_Concealer_Female_Pixel,2025-10-16,2025-10-16,132,tiktok

In [74]:
# events_list_1 = [{'ad_unit_id': '1845231507389538',
#   'event_name': 'XTH25-1529_Pizza_Company_OCT_test_dummy',
#   'event_date': '2025-10-07',
#   'ad_interaction_date': '2025-10-07',
#   'conversions': 19564,
#   'platform': 'tiktok'}]

In [75]:
# Convert the DataFrame to a list of dictionaries
events_list = PBA_result.to_dict(orient='records')
events_list

[{'ad_unit_id': '120232857671780122',
  'event_name': 'XTH25-1533_Srichand_Concealer_Female_Pixel',
  'event_date': '2025-10-16',
  'ad_interaction_date': '2025-10-16',
  'conversions': 221,
  'platform': 'facebook'},
 {'ad_unit_id': '1845588355711058',
  'event_name': 'XTH25-1533_Srichand_Concealer_Female_Pixel',
  'event_date': '2025-10-16',
  'ad_interaction_date': '2025-10-16',
  'conversions': 132,
  'platform': 'tiktok'}]

In [76]:
# Create the JSON structure
body = {"events": events_list}

In [77]:
# Convert to JSON string
json_output = json.dumps(body, indent=2)

In [78]:
base_url = "https://s2s.smartly.io/events/aggregated"

In [79]:
key_push = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA2YzYwYjk3LTIzMTYtNDUyZC1hOWJmLTAzMGUzYmQ3MDAwNSIsImNvbXBhbnlfaWQiOiI2ODA2MTA1ZGNmNWIxNzAwMzVjYTczZGYiLCJpYXQiOjE3NTkzMDU5Njl9.H6dcKUzUPK2HGkTdsUC40GHEW3H_JJ7yUmAJvPp1YJY'
# Set up headers
headers = {
    "Authorization": 'Bearer ' + key_push,
    "Content-Type": "application/json"
}

In [80]:
# # Create and send POST request
# response = requests.post(base_url, headers=headers, json=body)
# response.content

In [81]:
response = requests.post(base_url, headers=headers, json=body)

# Status information
print(f"Status Code: {response.status_code}")
print(f"Success: {response.ok}")
print(f"Reason: {response.reason}")

# Response content
print(f"\nRaw bytes: {response.content[:100]}...")  # First 100 bytes
print(f"Text: {response.text[:500]}")  # First 500 chars
print(f"JSON: {response.json()}")  # If JSON response

# Headers
print(f"\nResponse Headers: {dict(response.headers)}")
print(f"Content-Type: {response.headers.get('Content-Type')}")

# Performance
print(f"\nTime taken: {response.elapsed.total_seconds()} seconds")

# Request details
print(f"URL: {response.url}")
print(f"Encoding: {response.encoding}")

Status Code: 202
Success: True
Reason: Accepted

Raw bytes: b'{"status":"accepted"}'...
Text: {"status":"accepted"}
JSON: {'status': 'accepted'}

Response Headers: {'Server': 'nginx', 'Date': 'Fri, 17 Oct 2025 05:05:18 GMT', 'Content-Type': 'application/json', 'Content-Length': '21', 'Connection': 'keep-alive', 'content-security-policy': "default-src 'self'", 'x-dns-prefetch-control': 'off', 'expect-ct': 'max-age=0', 'x-frame-options': 'SAMEORIGIN', 'strict-transport-security': 'max-age=15552000; includeSubDomains', 'x-download-options': 'noopen', 'x-content-type-options': 'nosniff', 'x-permitted-cross-domain-policies': 'none', 'referrer-policy': 'no-referrer', 'x-xss-protection': '0', 'x-request-id': 'ecc0a7e8-405f-4886-8f96-06e108d350c4', 'x-message-id': 'aac50e5b-70f8-44a2-a9b5-bf0441bbf892', 'x-smartly-service': 'conveyor'}
Content-Type: application/json

Time taken: 1.066724 seconds
URL: https://s2s.smartly.io/events/aggregated
Encoding: utf-8

## Creating final dataframe for PBA input for Concealer Male and push into Smartly

In [54]:
# Create final structure
df_final = pd.DataFrame({
'ad_unit_id': result_end_Concealer_Male['Ad ID'],
'event_name': 'XTH25-1533_Srichand_Concealer_Male_Pixel',
'event_date': result_end_Concealer_Male['Date'],
'ad_interaction_date': result_end_Concealer_Male['Date'],
'conversions': result_end_Concealer_Male['PBA_INPUT'],
'platform': result_end_Concealer_Male['platform']
})

In [55]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ad_unit_id           21 non-null     object
 1   event_name           21 non-null     object
 2   event_date           21 non-null     datetime64[ns]
 3   ad_interaction_date  21 non-null     datetime64[ns]
 4   conversions          18 non-null     float64
 5   platform             21 non-null     object
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 1.1+ KB

In [56]:
df_final['event_date'] = pd.to_datetime(df_final['event_date'])
df_final['event_date'] = df_final['event_date'].dt.strftime('%Y-%m-%d')

df_final['ad_interaction_date'] = pd.to_datetime(df_final['ad_interaction_date'])
df_final['ad_interaction_date'] = df_final['ad_interaction_date'].dt.strftime('%Y-%m-%d')

In [57]:
# # Sort by date first to ensure earliest is first
# df_final = df_final.sort_values('event_date')

# # Replace inf and NaN with earliest valid conversion per platform
# def replace_invalid_with_earliest(group):
#   # Get first value that is neither inf nor NaN
#   valid_values = group[(~np.isinf(group)) & (~np.isnan(group))]
#   if len(valid_values) > 0:
#       first_valid = valid_values.iloc[0]
#       # Replace both inf and NaN
#       return group.replace([float('inf'), -float('inf')], first_valid).fillna(first_valid)
#   return group

# df_final['conversions'] = df_final.groupby('platform')['conversions'].transform(replace_invalid_with_earliest)

In [58]:
df_final[df_final['platform'] == 'facebook']['ad_unit_id'].unique()

array(['120233085296180122', '120233085296130122'], dtype=object)

In [59]:
df_final[df_final['platform'] == 'tiktok']['ad_unit_id'].unique()

array(['1845588047313057'], dtype=object)

In [60]:
# Define which IDs to keep
selected_ids = ['120233085296180122', '1845588047313057']

PBA_result = df_final[df_final['ad_unit_id'].isin(selected_ids)]

In [61]:
# PBA_result['conversions'] = PBA_result['conversions'].astype(int)
# PBA_result.info()

In [62]:
PBA_result['event_date'] = pd.to_datetime(PBA_result['event_date'])
PBA_result['event_date'] = PBA_result['event_date'].dt.strftime('%Y-%m-%d')

PBA_result['ad_interaction_date'] = pd.to_datetime(PBA_result['ad_interaction_date'])
PBA_result['ad_interaction_date'] = PBA_result['ad_interaction_date'].dt.strftime('%Y-%m-%d')

/tmp/ipython-input-1697232129.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PBA_result['event_date'] = pd.to_datetime(PBA_result['event_date'])
/tmp/ipython-input-1697232129.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PBA_result['event_date'] = PBA_result['event_date'].dt.strftime('%Y-%m-%d')
/tmp/ipython-input-1697232129.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PBA_result['ad_interaction_date'] = pd.to_datetime(PBA_result['ad_interaction_date'])
/tmp/ipython-input-1697232129.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PBA_result['ad_interaction_date'] = PBA_result['ad_interaction_date'].dt.strftime('%Y-%m-%d')

In [63]:
PBA_result

,ad_unit_id,event_name,event_date,ad_interaction_date,conversions,platform
0,120233085296180122,XTH25-1533_Srichand_Concealer_Male_Pixel,2025-10-09,2025-10-09,NaN,facebook
1,120233085296180122,XTH25-1533_Srichand_Concealer_Male_Pixel,2025-10-10,2025-10-10,15.795045,facebook
2,120233085296180122,XTH25-1533_Srichand_Concealer_Male_Pixel,2025-10-11,2025-10-11,37.468649,facebook
3,120233085296180122,XTH25-1533_Srichand_Concealer_Male_Pixel,2025-10-12,2025-10-12,47.485166,facebook
4,120233085296180122,XTH25-1533_Srichand_Concealer_Male_Pixel,2025-10-13,2025-10-13,45.131453,facebook
5,120233085296180122,XTH25-1533_Srichand_Concealer_Male_Pixel,2025-10-14,2025-10-14,43.103667,facebook
6,120233085296180122,XTH25-1533_Srichand_Concealer_Male_Pixel,2025-10-15,2025-10-15,78.185006,facebook
14,1845588047313057,XTH25-1533_Srichand_Concealer_Male_Pixel,2025-10-09,2025-10-09,NaN,tiktok
15,1845588047313057,XTH25-1533_Srichand_Concealer_Male_Pixel,2025-10-10,2025-10-10,58.236453,tiktok
16,1845588047313057,XTH25-1533_Srichand_Concealer_Male_Pixel,2025-10-11,2025-10-11,105.250040,tiktok
17,1845588047313057,XTH25-1533_Srichand_Concealer_Male_Pixel,2025-10-12,2025-10-12,72.330057,tiktok
18,1845588047313057,XTH25-1533_Srichand_Concealer_Male_Pixel,2025-10-13,2025-10-13,60.540439,tiktok
19,1845588047313057,XTH25-1533_Srichand_Concealer_Male_Pixel,2025-10-14,2025-10-14,50.798330,tiktok
20,1845588047313057,XTH25-1533_Srichand_Concealer_Male_Pixel,2025-10-15,2025-10-15,48.422521,tiktok

In [64]:
PBA_result.dropna(inplace = True)

/tmp/ipython-input-1057318816.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PBA_result.dropna(inplace = True)

In [65]:
PBA_result['conversions'] = PBA_result['conversions'].astype(int)
PBA_result.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 1 to 20
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ad_unit_id           12 non-null     object
 1   event_name           12 non-null     object
 2   event_date           12 non-null     object
 3   ad_interaction_date  12 non-null     object
 4   conversions          12 non-null     int64
 5   platform             12 non-null     object
dtypes: int64(1), object(5)
memory usage: 672.0+ bytes

/tmp/ipython-input-2482821460.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PBA_result['conversions'] = PBA_result['conversions'].astype(int)

In [66]:
PBA_result = PBA_result[(PBA_result['event_date'] == r_end_date)]
PBA_result

,ad_unit_id,event_name,event_date,ad_interaction_date,conversions,platform
6,120233085296180122,XTH25-1533_Srichand_Concealer_Male_Pixel,2025-10-15,2025-10-15,78,facebook
20,1845588047313057,XTH25-1533_Srichand_Concealer_Male_Pixel,2025-10-15,2025-10-15,48,tiktok

In [67]:
# events_list_1 = [{'ad_unit_id': '1845231507389538',
#   'event_name': 'XTH25-1529_Pizza_Company_OCT_test_dummy',
#   'event_date': '2025-10-07',
#   'ad_interaction_date': '2025-10-07',
#   'conversions': 19564,
#   'platform': 'tiktok'}]

In [68]:
# Convert the DataFrame to a list of dictionaries
events_list = PBA_result.to_dict(orient='records')
events_list

[{'ad_unit_id': '120233085296180122',
  'event_name': 'XTH25-1533_Srichand_Concealer_Male_Pixel',
  'event_date': '2025-10-15',
  'ad_interaction_date': '2025-10-15',
  'conversions': 78,
  'platform': 'facebook'},
 {'ad_unit_id': '1845588047313057',
  'event_name': 'XTH25-1533_Srichand_Concealer_Male_Pixel',
  'event_date': '2025-10-15',
  'ad_interaction_date': '2025-10-15',
  'conversions': 48,
  'platform': 'tiktok'}]

In [69]:
# Create the JSON structure
body = {"events": events_list}

In [70]:
# Convert to JSON string
json_output = json.dumps(body, indent=2)

In [71]:
base_url = "https://s2s.smartly.io/events/aggregated"

In [72]:
key_push = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA2YzYwYjk3LTIzMTYtNDUyZC1hOWJmLTAzMGUzYmQ3MDAwNSIsImNvbXBhbnlfaWQiOiI2ODA2MTA1ZGNmNWIxNzAwMzVjYTczZGYiLCJpYXQiOjE3NTkzMDU5Njl9.H6dcKUzUPK2HGkTdsUC40GHEW3H_JJ7yUmAJvPp1YJY'
# Set up headers
headers = {
    "Authorization": 'Bearer ' + key_push,
    "Content-Type": "application/json"
}

In [73]:
# # Create and send POST request
# response = requests.post(base_url, headers=headers, json=body)
# response.content

In [74]:
response = requests.post(base_url, headers=headers, json=body)

# Status information
print(f"Status Code: {response.status_code}")
print(f"Success: {response.ok}")
print(f"Reason: {response.reason}")

# Response content
print(f"\nRaw bytes: {response.content[:100]}...")  # First 100 bytes
print(f"Text: {response.text[:500]}")  # First 500 chars
print(f"JSON: {response.json()}")  # If JSON response

# Headers
print(f"\nResponse Headers: {dict(response.headers)}")
print(f"Content-Type: {response.headers.get('Content-Type')}")

# Performance
print(f"\nTime taken: {response.elapsed.total_seconds()} seconds")

# Request details
print(f"URL: {response.url}")
print(f"Encoding: {response.encoding}")

Status Code: 202
Success: True
Reason: Accepted

Raw bytes: b'{"status":"accepted"}'...
Text: {"status":"accepted"}
JSON: {'status': 'accepted'}

Response Headers: {'Server': 'nginx', 'Date': 'Thu, 16 Oct 2025 02:38:21 GMT', 'Content-Type': 'application/json', 'Content-Length': '21', 'Connection': 'keep-alive', 'content-security-policy': "default-src 'self'", 'x-dns-prefetch-control': 'off', 'expect-ct': 'max-age=0', 'x-frame-options': 'SAMEORIGIN', 'strict-transport-security': 'max-age=15552000; includeSubDomains', 'x-download-options': 'noopen', 'x-content-type-options': 'nosniff', 'x-permitted-cross-domain-policies': 'none', 'referrer-policy': 'no-referrer', 'x-xss-protection': '0', 'x-request-id': '4d3cb03a-4ebc-4347-83f4-dd543cd65d45', 'x-message-id': '90c68d81-1a90-46e8-87f2-8aaf26604593', 'x-smartly-service': 'conveyor'}
Content-Type: application/json

Time taken: 0.495536 seconds
URL: https://s2s.smartly.io/events/aggregated
Encoding: utf-8

## Creating final dataframe for PBA input for Foundation Female and push into Smartly

In [82]:
result_end_FOUNDATION_Female

,Advertising Platform,Campaign,Campaign ID,Ad Set ID,Ad Set,Ad ID,Date,Impressions,Spend,platform,PBA_INPUT
0,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120232852889220122,Magic Matte Audience 1: Core target Female,120232852889130122,2025-10-09,113575,1301.84,facebook,104.575089
1,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120232852889220122,Magic Matte Audience 1: Core target Female,120232852889130122,2025-10-10,122353,1196.00,facebook,161.451231
2,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120232852889220122,Magic Matte Audience 1: Core target Female,120232852889130122,2025-10-11,82873,763.09,facebook,128.629529
3,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120232852889220122,Magic Matte Audience 1: Core target Female,120232852889130122,2025-10-12,96821,880.04,facebook,197.961587
4,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120232852889220122,Magic Matte Audience 1: Core target Female,120232852889130122,2025-10-13,84556,758.37,facebook,173.504436
5,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120232852889220122,Magic Matte Audience 1: Core target Female,120232852889130122,2025-10-14,92352,802.72,facebook,159.828903
6,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120232852889220122,Magic Matte Audience 1: Core target Female,120232852889130122,2025-10-15,204689,1900.13,facebook,357.080139
7,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120232852889220122,Magic Matte Audience 1: Core target Female,120232852889130122,2025-10-16,236138,2201.59,facebook,278.385570
8,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120233010669040122,Magic Matte Audience 2: RTG,120233010669030122,2025-10-10,46737,433.46,facebook,161.451231
9,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120233010669040122,Magic Matte Audience 2: RTG,120233010669030122,2025-10-11,75614,692.60,facebook,128.629529
10,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120233010669040122,Magic Matte Audience 2: RTG,120233010669030122,2025-10-12,132364,1196.48,facebook,197.961587
11,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120233010669040122,Magic Matte Audience 2: RTG,120233010669030122,2025-10-13,131104,1164.10,facebook,173.504436
12,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120233010669040122,Magic Matte Audience 2: RTG,120233010669030122,2025-10-14,111200,960.49,facebook,159.828903
13,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120233010669040122,Magic Matte Audience 2: RTG,120233010669030122,2025-10-15,219680,2015.24,facebook,357.080139
14,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120232852889250122,120233010669040122,Magic Matte Audience 2: RTG,120233010669030122,2025-10-16,231136,2153.85,facebook,278.385570
15,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845308633305170,Magic Matte Audience 1: Core target - Female,1845403802316866,2025-10-09,158817,1772.41,tiktok,156.140122
16,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845308633305170,Magic Matte Audience 1: Core target - Female,1845403802316866,2025-10-10,133107,1532.83,tiktok,104.596139
17,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845308633305170,Magic Matte Audience 1: Core target - Female,1845403802316866,2025-10-11,133699,1271.53,tiktok,89.167927
18,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845308633305170,Magic Matte Audience 1: Core target - Female,1845403802316866,2025-10-12,161698,1432.02,tiktok,92.490436
19,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845308633305170,Magic Matte Audience 1: Core target - Female,1845403802316866,2025-10-13,166314,1466.04,tiktok,87.900717
20,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845308633305170,Magic Matte Audience 1: Core target - Female,1845403802316866,2025-10-14,147049,1476.33,tiktok,66.834142
21,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845308633305170,Magic Matte Audience 1: Core target - Female,1845403802316866,2025-10-15,274399,3180.54,tiktok,151.194731
22,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845308633305170,Magic Matte Audience 1: Core target - Female,1845403802316866,2025-10-16,272421,3050.07,tiktok,55.734069
23,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845588535235777,Magic Matte Audience 2: RTG,1845588535235793,2025-10-10,17820,226.37,tiktok,104.596139
24,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845588535235777,Magic Matte Audience 2: RTG,1845588535235793,2025-10-11,46943,446.86,tiktok,89.167927
25,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845588535235777,Magic Matte Audience 2: RTG,1845588535235793,2025-10-12,37520,334.60,tiktok,92.490436
26,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845588535235777,Magic Matte Audience 2: RTG,1845588535235793,2025-10-13,33167,294.28,tiktok,87.900717
27,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845588535235777,Magic Matte Audience 2: RTG,1845588535235793,2025-10-14,28552,286.19,tiktok,66.834142
28,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845588535235777,Magic Matte Audience 2: RTG,1845588535235793,2025-10-15,32697,377.92,tiktok,151.194731
29,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845308633305154,1845588535235777,Magic Matte Audience 2: RTG,1845588535235793,2025-10-16,37240,411.05,tiktok,55.734069

In [83]:
# Create final structure
df_final = pd.DataFrame({
'ad_unit_id': result_end_FOUNDATION_Female['Ad ID'],
'event_name': 'XTH25-1533_Srichand_Foundation_Female_Pixel',
'event_date': result_end_FOUNDATION_Female['Date'],
'ad_interaction_date': result_end_FOUNDATION_Female['Date'],
'conversions': result_end_FOUNDATION_Female['PBA_INPUT'],
'platform': result_end_FOUNDATION_Female['platform']
})

In [84]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ad_unit_id           30 non-null     object
 1   event_name           30 non-null     object
 2   event_date           30 non-null     datetime64[ns]
 3   ad_interaction_date  30 non-null     datetime64[ns]
 4   conversions          30 non-null     float64
 5   platform             30 non-null     object
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 1.5+ KB

In [85]:
df_final['event_date'] = pd.to_datetime(df_final['event_date'])
df_final['event_date'] = df_final['event_date'].dt.strftime('%Y-%m-%d')

df_final['ad_interaction_date'] = pd.to_datetime(df_final['ad_interaction_date'])
df_final['ad_interaction_date'] = df_final['ad_interaction_date'].dt.strftime('%Y-%m-%d')

In [86]:
df_final

,ad_unit_id,event_name,event_date,ad_interaction_date,conversions,platform
0,120232852889130122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-09,2025-10-09,104.575089,facebook
1,120232852889130122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-10,2025-10-10,161.451231,facebook
2,120232852889130122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-11,2025-10-11,128.629529,facebook
3,120232852889130122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-12,2025-10-12,197.961587,facebook
4,120232852889130122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-13,2025-10-13,173.504436,facebook
5,120232852889130122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-14,2025-10-14,159.828903,facebook
6,120232852889130122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-15,2025-10-15,357.080139,facebook
7,120232852889130122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-16,2025-10-16,278.385570,facebook
8,120233010669030122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-10,2025-10-10,161.451231,facebook
9,120233010669030122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-11,2025-10-11,128.629529,facebook
10,120233010669030122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-12,2025-10-12,197.961587,facebook
11,120233010669030122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-13,2025-10-13,173.504436,facebook
12,120233010669030122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-14,2025-10-14,159.828903,facebook
13,120233010669030122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-15,2025-10-15,357.080139,facebook
14,120233010669030122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-16,2025-10-16,278.385570,facebook
15,1845403802316866,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-09,2025-10-09,156.140122,tiktok
16,1845403802316866,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-10,2025-10-10,104.596139,tiktok
17,1845403802316866,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-11,2025-10-11,89.167927,tiktok
18,1845403802316866,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-12,2025-10-12,92.490436,tiktok
19,1845403802316866,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-13,2025-10-13,87.900717,tiktok
20,1845403802316866,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-14,2025-10-14,66.834142,tiktok
21,1845403802316866,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-15,2025-10-15,151.194731,tiktok
22,1845403802316866,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-16,2025-10-16,55.734069,tiktok
23,1845588535235793,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-10,2025-10-10,104.596139,tiktok
24,1845588535235793,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-11,2025-10-11,89.167927,tiktok
25,1845588535235793,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-12,2025-10-12,92.490436,tiktok
26,1845588535235793,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-13,2025-10-13,87.900717,tiktok
27,1845588535235793,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-14,2025-10-14,66.834142,tiktok
28,1845588535235793,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-15,2025-10-15,151.194731,tiktok
29,1845588535235793,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-16,2025-10-16,55.734069,tiktok

In [87]:
# # Sort by date first to ensure earliest is first
# df_final = df_final.sort_values('event_date')

# # Replace inf and NaN with earliest valid conversion per platform
# def replace_invalid_with_earliest(group):
#   # Get first value that is neither inf nor NaN
#   valid_values = group[(~np.isinf(group)) & (~np.isnan(group))]
#   if len(valid_values) > 0:
#       first_valid = valid_values.iloc[0]
#       # Replace both inf and NaN
#       return group.replace([float('inf'), -float('inf')], first_valid).fillna(first_valid)
#   return group

# df_final['conversions'] = df_final.groupby('platform')['conversions'].transform(replace_invalid_with_earliest)

In [88]:
df_final[df_final['platform'] == 'facebook']['ad_unit_id'].unique()

array(['120232852889130122', '120233010669030122'], dtype=object)

In [89]:
df_final[df_final['platform'] == 'tiktok']['ad_unit_id'].unique()

array(['1845403802316866', '1845588535235793'], dtype=object)

In [90]:
# Define which IDs to keep
selected_ids = ['120232852889130122', '1845403802316866']

PBA_result = df_final[df_final['ad_unit_id'].isin(selected_ids)]

In [91]:
PBA_result['conversions'] = PBA_result['conversions'].astype(int)
PBA_result.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16 entries, 0 to 22
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ad_unit_id           16 non-null     object
 1   event_name           16 non-null     object
 2   event_date           16 non-null     object
 3   ad_interaction_date  16 non-null     object
 4   conversions          16 non-null     int64
 5   platform             16 non-null     object
dtypes: int64(1), object(5)
memory usage: 896.0+ bytes

/tmp/ipython-input-2482821460.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PBA_result['conversions'] = PBA_result['conversions'].astype(int)

In [92]:
PBA_result['event_date'] = pd.to_datetime(PBA_result['event_date'])
PBA_result['event_date'] = PBA_result['event_date'].dt.strftime('%Y-%m-%d')

PBA_result['ad_interaction_date'] = pd.to_datetime(PBA_result['ad_interaction_date'])
PBA_result['ad_interaction_date'] = PBA_result['ad_interaction_date'].dt.strftime('%Y-%m-%d')

/tmp/ipython-input-1697232129.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PBA_result['event_date'] = pd.to_datetime(PBA_result['event_date'])
/tmp/ipython-input-1697232129.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PBA_result['event_date'] = PBA_result['event_date'].dt.strftime('%Y-%m-%d')
/tmp/ipython-input-1697232129.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PBA_result['ad_interaction_date'] = pd.to_datetime(PBA_result['ad_interaction_date'])
/tmp/ipython-input-1697232129.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PBA_result['ad_interaction_date'] = PBA_result['ad_interaction_date'].dt.strftime('%Y-%m-%d')

In [93]:
PBA_result

,ad_unit_id,event_name,event_date,ad_interaction_date,conversions,platform
0,120232852889130122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-09,2025-10-09,104,facebook
1,120232852889130122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-10,2025-10-10,161,facebook
2,120232852889130122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-11,2025-10-11,128,facebook
3,120232852889130122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-12,2025-10-12,197,facebook
4,120232852889130122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-13,2025-10-13,173,facebook
5,120232852889130122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-14,2025-10-14,159,facebook
6,120232852889130122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-15,2025-10-15,357,facebook
7,120232852889130122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-16,2025-10-16,278,facebook
15,1845403802316866,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-09,2025-10-09,156,tiktok
16,1845403802316866,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-10,2025-10-10,104,tiktok
17,1845403802316866,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-11,2025-10-11,89,tiktok
18,1845403802316866,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-12,2025-10-12,92,tiktok
19,1845403802316866,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-13,2025-10-13,87,tiktok
20,1845403802316866,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-14,2025-10-14,66,tiktok
21,1845403802316866,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-15,2025-10-15,151,tiktok
22,1845403802316866,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-16,2025-10-16,55,tiktok

In [94]:
PBA_result.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16 entries, 0 to 22
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ad_unit_id           16 non-null     object
 1   event_name           16 non-null     object
 2   event_date           16 non-null     object
 3   ad_interaction_date  16 non-null     object
 4   conversions          16 non-null     int64
 5   platform             16 non-null     object
dtypes: int64(1), object(5)
memory usage: 1.4+ KB

In [95]:
PBA_result = PBA_result[(PBA_result['event_date'] == r_end_date)]
PBA_result

,ad_unit_id,event_name,event_date,ad_interaction_date,conversions,platform
7,120232852889130122,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-16,2025-10-16,278,facebook
22,1845403802316866,XTH25-1533_Srichand_Foundation_Female_Pixel,2025-10-16,2025-10-16,55,tiktok

In [96]:
# events_list_1 = [{'ad_unit_id': '1845231507389538',
#   'event_name': 'XTH25-1529_Pizza_Company_OCT_test_dummy',
#   'event_date': '2025-10-07',
#   'ad_interaction_date': '2025-10-07',
#   'conversions': 19564,
#   'platform': 'tiktok'}]

In [97]:
# Convert the DataFrame to a list of dictionaries
events_list = PBA_result.to_dict(orient='records')
events_list

[{'ad_unit_id': '120232852889130122',
  'event_name': 'XTH25-1533_Srichand_Foundation_Female_Pixel',
  'event_date': '2025-10-16',
  'ad_interaction_date': '2025-10-16',
  'conversions': 278,
  'platform': 'facebook'},
 {'ad_unit_id': '1845403802316866',
  'event_name': 'XTH25-1533_Srichand_Foundation_Female_Pixel',
  'event_date': '2025-10-16',
  'ad_interaction_date': '2025-10-16',
  'conversions': 55,
  'platform': 'tiktok'}]

In [98]:
# Create the JSON structure
body = {"events": events_list}

In [99]:
# Convert to JSON string
json_output = json.dumps(body, indent=2)

In [100]:
base_url = "https://s2s.smartly.io/events/aggregated"

In [101]:
key_push = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA2YzYwYjk3LTIzMTYtNDUyZC1hOWJmLTAzMGUzYmQ3MDAwNSIsImNvbXBhbnlfaWQiOiI2ODA2MTA1ZGNmNWIxNzAwMzVjYTczZGYiLCJpYXQiOjE3NTkzMDU5Njl9.H6dcKUzUPK2HGkTdsUC40GHEW3H_JJ7yUmAJvPp1YJY'
# Set up headers
headers = {
    "Authorization": 'Bearer ' + key_push,
    "Content-Type": "application/json"
}

In [102]:
# # Create and send POST request
# response = requests.post(base_url, headers=headers, json=body)
# response.content

In [103]:
response = requests.post(base_url, headers=headers, json=body)

# Status information
print(f"Status Code: {response.status_code}")
print(f"Success: {response.ok}")
print(f"Reason: {response.reason}")

# Response content
print(f"\nRaw bytes: {response.content[:100]}...")  # First 100 bytes
print(f"Text: {response.text[:500]}")  # First 500 chars
print(f"JSON: {response.json()}")  # If JSON response

# Headers
print(f"\nResponse Headers: {dict(response.headers)}")
print(f"Content-Type: {response.headers.get('Content-Type')}")

# Performance
print(f"\nTime taken: {response.elapsed.total_seconds()} seconds")

# Request details
print(f"URL: {response.url}")
print(f"Encoding: {response.encoding}")

Status Code: 202
Success: True
Reason: Accepted

Raw bytes: b'{"status":"accepted"}'...
Text: {"status":"accepted"}
JSON: {'status': 'accepted'}

Response Headers: {'Server': 'nginx', 'Date': 'Fri, 17 Oct 2025 05:05:45 GMT', 'Content-Type': 'application/json', 'Content-Length': '21', 'Connection': 'keep-alive', 'content-security-policy': "default-src 'self'", 'x-dns-prefetch-control': 'off', 'expect-ct': 'max-age=0', 'x-frame-options': 'SAMEORIGIN', 'strict-transport-security': 'max-age=15552000; includeSubDomains', 'x-download-options': 'noopen', 'x-content-type-options': 'nosniff', 'x-permitted-cross-domain-policies': 'none', 'referrer-policy': 'no-referrer', 'x-xss-protection': '0', 'x-request-id': 'f9501a4b-dfdf-4582-98ef-5a6f469cc9e9', 'x-message-id': 'baddc337-3be5-4074-a0a7-43c08af43e8a', 'x-smartly-service': 'conveyor'}
Content-Type: application/json

Time taken: 0.763298 seconds
URL: https://s2s.smartly.io/events/aggregated
Encoding: utf-8

## Creating final dataframe for PBA input for Foundation Male and push into Smartly

In [97]:
result_end_FOUNDATION_Male

,Advertising Platform,Campaign,Campaign ID,Ad Set ID,Ad Set,Ad ID,Impressions,Spend,platform,Date,PBA_INPUT
0,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233084770160122,120233084770170122,Magic Matte Audience 1: Core target Male IG,120233084770190122,0,0.00,facebook,2025-10-09,NaN
1,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233084770160122,120233084770170122,Magic Matte Audience 1: Core target Male IG,120233084770190122,0,0.00,facebook,2025-10-10,29.118691
2,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233084770160122,120233084770170122,Magic Matte Audience 1: Core target Male IG,120233084770190122,0,0.00,facebook,2025-10-11,70.500887
3,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233084770160122,120233084770170122,Magic Matte Audience 1: Core target Male IG,120233084770190122,0,0.00,facebook,2025-10-12,88.605201
4,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233084770160122,120233084770170122,Magic Matte Audience 1: Core target Male IG,120233084770190122,0,0.00,facebook,2025-10-13,88.746624
5,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233084770160122,120233084770170122,Magic Matte Audience 1: Core target Male IG,120233084770190122,0,0.00,facebook,2025-10-14,74.771011
6,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233084770160122,120233084770170122,Magic Matte Audience 1: Core target Male IG,120233084770190122,0,0.00,facebook,2025-10-15,136.614560
7,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233084770160122,120233084770200122,Magic Matte Audience 1: Core target Male FB,120233084770230122,530501,4687.51,facebook,2025-10-09,NaN
8,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233084770160122,120233084770200122,Magic Matte Audience 1: Core target Male FB,120233084770230122,530501,4687.51,facebook,2025-10-10,29.118691
9,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233084770160122,120233084770200122,Magic Matte Audience 1: Core target Male FB,120233084770230122,530501,4687.51,facebook,2025-10-11,70.500887
10,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233084770160122,120233084770200122,Magic Matte Audience 1: Core target Male FB,120233084770230122,530501,4687.51,facebook,2025-10-12,88.605201
11,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233084770160122,120233084770200122,Magic Matte Audience 1: Core target Male FB,120233084770230122,530501,4687.51,facebook,2025-10-13,88.746624
12,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233084770160122,120233084770200122,Magic Matte Audience 1: Core target Male FB,120233084770230122,530501,4687.51,facebook,2025-10-14,74.771011
13,facebook,XTH25-1533_Srichand_Magic Matte Collection 6s ...,120233084770160122,120233084770200122,Magic Matte Audience 1: Core target Male FB,120233084770230122,530501,4687.51,facebook,2025-10-15,136.614560
14,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995522,560569,4670.85,tiktok,2025-10-09,NaN
15,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995522,560569,4670.85,tiktok,2025-10-10,34.386823
16,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995522,560569,4670.85,tiktok,2025-10-11,87.420376
17,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995522,560569,4670.85,tiktok,2025-10-12,65.869211
18,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995522,560569,4670.85,tiktok,2025-10-13,58.889636
19,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995522,560569,4670.85,tiktok,2025-10-14,49.458182
20,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995522,560569,4670.85,tiktok,2025-10-15,60.979662
21,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995538,0,0.00,tiktok,2025-10-09,NaN
22,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995538,0,0.00,tiktok,2025-10-10,34.386823
23,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995538,0,0.00,tiktok,2025-10-11,87.420376
24,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995538,0,0.00,tiktok,2025-10-12,65.869211
25,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995538,0,0.00,tiktok,2025-10-13,58.889636
26,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995538,0,0.00,tiktok,2025-10-14,49.458182
27,tiktok,XTH25-1533_Srichand_Magic Matte Collection 6s ...,1845587525994658,1845587525994674,Magic Matte Audience 1: Core target - Male,1845587525995538,0,0.00,tiktok,2025-10-15,60.979662

In [98]:
# Create final structure
df_final = pd.DataFrame({
'ad_unit_id': result_end_FOUNDATION_Male['Ad ID'],
'event_name': 'XTH25-1533_Srichand_Foundation_Male_Pixel',
'event_date': result_end_FOUNDATION_Male['Date'],
'ad_interaction_date': result_end_FOUNDATION_Male['Date'],
'conversions': result_end_FOUNDATION_Male['PBA_INPUT'],
'platform': result_end_FOUNDATION_Male['platform']
})

In [99]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ad_unit_id           28 non-null     object
 1   event_name           28 non-null     object
 2   event_date           28 non-null     datetime64[ns]
 3   ad_interaction_date  28 non-null     datetime64[ns]
 4   conversions          24 non-null     float64
 5   platform             28 non-null     object
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 1.4+ KB

In [100]:
df_final['event_date'] = pd.to_datetime(df_final['event_date'])
df_final['event_date'] = df_final['event_date'].dt.strftime('%Y-%m-%d')

df_final['ad_interaction_date'] = pd.to_datetime(df_final['ad_interaction_date'])
df_final['ad_interaction_date'] = df_final['ad_interaction_date'].dt.strftime('%Y-%m-%d')

In [101]:
# # Sort by date first to ensure earliest is first
# df_final = df_final.sort_values('event_date')

# # Replace inf and NaN with earliest valid conversion per platform
# def replace_invalid_with_earliest(group):
#   # Get first value that is neither inf nor NaN
#   valid_values = group[(~np.isinf(group)) & (~np.isnan(group))]
#   if len(valid_values) > 0:
#       first_valid = valid_values.iloc[0]
#       # Replace both inf and NaN
#       return group.replace([float('inf'), -float('inf')], first_valid).fillna(first_valid)
#   return group

# df_final['conversions'] = df_final.groupby('platform')['conversions'].transform(replace_invalid_with_earliest)

In [102]:
df_final[df_final['platform'] == 'facebook']['ad_unit_id'].unique()

array(['120233084770190122', '120233084770230122'], dtype=object)

In [103]:
df_final[df_final['platform'] == 'tiktok']['ad_unit_id'].unique()

array(['1845587525995522', '1845587525995538'], dtype=object)

In [104]:
# Define which IDs to keep
selected_ids = ['120233084770230122', '1845587525995522']

PBA_result = df_final[df_final['ad_unit_id'].isin(selected_ids)]

In [105]:
PBA_result.dropna(inplace =True)

/tmp/ipython-input-2328829831.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PBA_result.dropna(inplace =True)

In [106]:
PBA_result['conversions'] = PBA_result['conversions'].astype(int)
PBA_result.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 8 to 20
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ad_unit_id           12 non-null     object
 1   event_name           12 non-null     object
 2   event_date           12 non-null     object
 3   ad_interaction_date  12 non-null     object
 4   conversions          12 non-null     int64
 5   platform             12 non-null     object
dtypes: int64(1), object(5)
memory usage: 672.0+ bytes

/tmp/ipython-input-2482821460.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PBA_result['conversions'] = PBA_result['conversions'].astype(int)

In [107]:
PBA_result['event_date'] = pd.to_datetime(PBA_result['event_date'])
PBA_result['event_date'] = PBA_result['event_date'].dt.strftime('%Y-%m-%d')

PBA_result['ad_interaction_date'] = pd.to_datetime(PBA_result['ad_interaction_date'])
PBA_result['ad_interaction_date'] = PBA_result['ad_interaction_date'].dt.strftime('%Y-%m-%d')

/tmp/ipython-input-1697232129.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PBA_result['event_date'] = pd.to_datetime(PBA_result['event_date'])
/tmp/ipython-input-1697232129.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PBA_result['event_date'] = PBA_result['event_date'].dt.strftime('%Y-%m-%d')
/tmp/ipython-input-1697232129.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PBA_result['ad_interaction_date'] = pd.to_datetime(PBA_result['ad_interaction_date'])
/tmp/ipython-input-1697232129.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PBA_result['ad_interaction_date'] = PBA_result['ad_interaction_date'].dt.strftime('%Y-%m-%d')

In [108]:
PBA_result

,ad_unit_id,event_name,event_date,ad_interaction_date,conversions,platform
8,120233084770230122,XTH25-1533_Srichand_Foundation_Male_Pixel,2025-10-10,2025-10-10,29,facebook
9,120233084770230122,XTH25-1533_Srichand_Foundation_Male_Pixel,2025-10-11,2025-10-11,70,facebook
10,120233084770230122,XTH25-1533_Srichand_Foundation_Male_Pixel,2025-10-12,2025-10-12,88,facebook
11,120233084770230122,XTH25-1533_Srichand_Foundation_Male_Pixel,2025-10-13,2025-10-13,88,facebook
12,120233084770230122,XTH25-1533_Srichand_Foundation_Male_Pixel,2025-10-14,2025-10-14,74,facebook
13,120233084770230122,XTH25-1533_Srichand_Foundation_Male_Pixel,2025-10-15,2025-10-15,136,facebook
15,1845587525995522,XTH25-1533_Srichand_Foundation_Male_Pixel,2025-10-10,2025-10-10,34,tiktok
16,1845587525995522,XTH25-1533_Srichand_Foundation_Male_Pixel,2025-10-11,2025-10-11,87,tiktok
17,1845587525995522,XTH25-1533_Srichand_Foundation_Male_Pixel,2025-10-12,2025-10-12,65,tiktok
18,1845587525995522,XTH25-1533_Srichand_Foundation_Male_Pixel,2025-10-13,2025-10-13,58,tiktok
19,1845587525995522,XTH25-1533_Srichand_Foundation_Male_Pixel,2025-10-14,2025-10-14,49,tiktok
20,1845587525995522,XTH25-1533_Srichand_Foundation_Male_Pixel,2025-10-15,2025-10-15,60,tiktok

In [109]:
PBA_result.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 8 to 20
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ad_unit_id           12 non-null     object
 1   event_name           12 non-null     object
 2   event_date           12 non-null     object
 3   ad_interaction_date  12 non-null     object
 4   conversions          12 non-null     int64
 5   platform             12 non-null     object
dtypes: int64(1), object(5)
memory usage: 972.0+ bytes

In [119]:
PBA_result = PBA_result[(PBA_result['event_date'] == r_end_date)]
PBA_result

,ad_unit_id,event_name,event_date,ad_interaction_date,conversions,platform
13,120233084770230122,XTH25-1533_Srichand_Foundation_Male_Pixel,2025-10-15,2025-10-15,136,facebook
20,1845587525995522,XTH25-1533_Srichand_Foundation_Male_Pixel,2025-10-15,2025-10-15,60,tiktok

In [111]:
# events_list_1 = [{'ad_unit_id': '1845231507389538',
#   'event_name': 'XTH25-1529_Pizza_Company_OCT_test_dummy',
#   'event_date': '2025-10-07',
#   'ad_interaction_date': '2025-10-07',
#   'conversions': 19564,
#   'platform': 'tiktok'}]

In [112]:
# Convert the DataFrame to a list of dictionaries
events_list = PBA_result.to_dict(orient='records')
events_list

[{'ad_unit_id': '120233084770230122',
  'event_name': 'XTH25-1533_Srichand_Foundation_Male_Pixel',
  'event_date': '2025-10-10',
  'ad_interaction_date': '2025-10-10',
  'conversions': 29,
  'platform': 'facebook'},
 {'ad_unit_id': '120233084770230122',
  'event_name': 'XTH25-1533_Srichand_Foundation_Male_Pixel',
  'event_date': '2025-10-11',
  'ad_interaction_date': '2025-10-11',
  'conversions': 70,
  'platform': 'facebook'},
 {'ad_unit_id': '120233084770230122',
  'event_name': 'XTH25-1533_Srichand_Foundation_Male_Pixel',
  'event_date': '2025-10-12',
  'ad_interaction_date': '2025-10-12',
  'conversions': 88,
  'platform': 'facebook'},
 {'ad_unit_id': '120233084770230122',
  'event_name': 'XTH25-1533_Srichand_Foundation_Male_Pixel',
  'event_date': '2025-10-13',
  'ad_interaction_date': '2025-10-13',
  'conversions': 88,
  'platform': 'facebook'},
 {'ad_unit_id': '120233084770230122',
  'event_name': 'XTH25-1533_Srichand_Foundation_Male_Pixel',
  'event_date': '2025-10-14',
  'ad_interaction_date': '2025-10-14',
  'conversions': 74,
  'platform': 'facebook'},
 {'ad_unit_id': '120233084770230122',
  'event_name': 'XTH25-1533_Srichand_Foundation_Male_Pixel',
  'event_date': '2025-10-15',
  'ad_interaction_date': '2025-10-15',
  'conversions': 136,
  'platform': 'facebook'},
 {'ad_unit_id': '1845587525995522',
  'event_name': 'XTH25-1533_Srichand_Foundation_Male_Pixel',
  'event_date': '2025-10-10',
  'ad_interaction_date': '2025-10-10',
  'conversions': 34,
  'platform': 'tiktok'},
 {'ad_unit_id': '1845587525995522',
  'event_name': 'XTH25-1533_Srichand_Foundation_Male_Pixel',
  'event_date': '2025-10-11',
  'ad_interaction_date': '2025-10-11',
  'conversions': 87,
  'platform': 'tiktok'},
 {'ad_unit_id': '1845587525995522',
  'event_name': 'XTH25-1533_Srichand_Foundation_Male_Pixel',
  'event_date': '2025-10-12',
  'ad_interaction_date': '2025-10-12',
  'conversions': 65,
  'platform': 'tiktok'},
 {'ad_unit_id': '1845587525995522',
  'event_name': 'XTH25-1533_Srichand_Foundation_Male_Pixel',
  'event_date': '2025-10-13',
  'ad_interaction_date': '2025-10-13',
  'conversions': 58,
  'platform': 'tiktok'},
 {'ad_unit_id': '1845587525995522',
  'event_name': 'XTH25-1533_Srichand_Foundation_Male_Pixel',
  'event_date': '2025-10-14',
  'ad_interaction_date': '2025-10-14',
  'conversions': 49,
  'platform': 'tiktok'},
 {'ad_unit_id': '1845587525995522',
  'event_name': 'XTH25-1533_Srichand_Foundation_Male_Pixel',
  'event_date': '2025-10-15',
  'ad_interaction_date': '2025-10-15',
  'conversions': 60,
  'platform': 'tiktok'}]

In [113]:
# Create the JSON structure
body = {"events": events_list}

In [114]:
# Convert to JSON string
json_output = json.dumps(body, indent=2)

In [115]:
base_url = "https://s2s.smartly.io/events/aggregated"

In [116]:
key_push = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA2YzYwYjk3LTIzMTYtNDUyZC1hOWJmLTAzMGUzYmQ3MDAwNSIsImNvbXBhbnlfaWQiOiI2ODA2MTA1ZGNmNWIxNzAwMzVjYTczZGYiLCJpYXQiOjE3NTkzMDU5Njl9.H6dcKUzUPK2HGkTdsUC40GHEW3H_JJ7yUmAJvPp1YJY'
# Set up headers
headers = {
    "Authorization": 'Bearer ' + key_push,
    "Content-Type": "application/json"
}

In [117]:
# # Create and send POST request
# response = requests.post(base_url, headers=headers, json=body)
# response.content

In [118]:
response = requests.post(base_url, headers=headers, json=body)

# Status information
print(f"Status Code: {response.status_code}")
print(f"Success: {response.ok}")
print(f"Reason: {response.reason}")

# Response content
print(f"\nRaw bytes: {response.content[:100]}...")  # First 100 bytes
print(f"Text: {response.text[:500]}")  # First 500 chars
print(f"JSON: {response.json()}")  # If JSON response

# Headers
print(f"\nResponse Headers: {dict(response.headers)}")
print(f"Content-Type: {response.headers.get('Content-Type')}")

# Performance
print(f"\nTime taken: {response.elapsed.total_seconds()} seconds")

# Request details
print(f"URL: {response.url}")
print(f"Encoding: {response.encoding}")

Status Code: 202
Success: True
Reason: Accepted

Raw bytes: b'{"status":"accepted"}'...
Text: {"status":"accepted"}
JSON: {'status': 'accepted'}

Response Headers: {'Server': 'nginx', 'Date': 'Thu, 16 Oct 2025 02:39:28 GMT', 'Content-Type': 'application/json', 'Content-Length': '21', 'Connection': 'keep-alive', 'content-security-policy': "default-src 'self'", 'x-dns-prefetch-control': 'off', 'expect-ct': 'max-age=0', 'x-frame-options': 'SAMEORIGIN', 'strict-transport-security': 'max-age=15552000; includeSubDomains', 'x-download-options': 'noopen', 'x-content-type-options': 'nosniff', 'x-permitted-cross-domain-policies': 'none', 'referrer-policy': 'no-referrer', 'x-xss-protection': '0', 'x-request-id': 'ad62f7c5-d592-45dc-9958-58b0e2aeae38', 'x-message-id': '12a679c1-bce0-46a9-8639-19d382142968', 'x-smartly-service': 'conveyor'}
Content-Type: application/json

Time taken: 0.478734 seconds
URL: https://s2s.smartly.io/events/aggregated
Encoding: utf-8